### ISSUE TITLE
DOC for "Specify scenarios"

### ISSUE THREAD

**Issue by JohnHuahuaZhan** [getgauge/gauge#1003]
it does not work to run scenarios with zero-indexed number of scenarios.it seems like line number
<img width="1270" alt="2018-04-07 13 01 11" src="https://user-images.githubusercontent.com/11831897/38451524-e1a9e4f8-3a63-11e8-85a0-355f60a855df.png">

**Comment by sriv** [comment]
Thanks, that is a mistake in the doc, we will correct it. Gauge looks at line no, not scenario index.

Context: gauge used to honour index based scenario exeuction (long back!) but [we moved](https://github.com/getgauge/gauge/issues/440) to line numbers, since it was easier to determine the line no, than count index of scenarios.
