### ISSUE TITLE
Should support \t as a csv delimiter

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1100]
**Expected behavior**
Should be able to use a tab as a delimiter

**Actual behavior**
Though the delimiter is configurable, a currently am not able to specify tab as a delimeter

**Steps to replicate**
* Create a `gauge-js` project
* Add a csv file with values
* Use a column from the csv in a spec file
* configure `csv_delimiter` to `\t`
* Separate the column values using tab
* Reload the project
> The dynamic parameter is no longer recognized

Child of #1067

**Comment by ajoecker** [comment]
I have a working solution for this, but it seems that special delimiters like `\t` must be masked in the property file like `csv_delimiter = '\t'`
Otherwise with `csv_delimiter = \t` the property gets ignored (?) so that it seems the `tableParser.go#convertCsvToTable` function is not reading it ?!
Can this be ?

**Comment by nehashri** [comment]
@ajoecker I still don't see if this needs to be worked upon. As I pointed out in this comment(https://github.com/getgauge/gauge/issues/1067#issuecomment-400997174) we may not need to support this at all. I don't see a valid usecase for someone needing to use tabs as delimiters in CSV. Until someone points out a valid usecase, I think we can just let this be.

**Comment by ajoecker** [comment]
yeah i agreed with you on that. 

The thing is that we might need a discussion, whether this option is of general use then. Because if gauge allows to configure the delimiter, but then restrict it to certain values, then the general option might be useless. 

It is in general a broader discussion (see https://stackoverflow.com/questions/10140999/csv-with-comma-or-semicolon) 

My point is that gauge should be consistent.

so possible solutions I see would be:

1. Revert the change and do not allow any configuration. Then it is on the user to use `"` for all the fields with a `,` 
2. Make sure that all options are parseable let the user use any csv file she wants.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
