### ISSUE TITLE
File parameter specified in special parameter Table(csv) should have the same behavior as the inline table

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1107]
**Expected behavior**
When contents of the table are printed both should have the same behavior

**Actual behavior**
The csv table parameter prints the file path instead of the content, whereas the inline table parameter prints the content of the file

**Steps to replicate**
* Create a `gauge-js` project
* Create a file `something.txt` with content `content`
* Create a csv
```
HEAD,HEAD2
fsdsdfdfsfsdffsdf,<file:specs/something.txt>
```
* Use this in a step as a parameter
* In the implementation print the contents of the table
```
  table.rows.forEach(function (row) {
    console.log(row.cells[0])
    console.log(row.cells[1])
  });
```
* Run the specs
> The printed output contains the file path

**Version**
```
Gauge version: 1.0.1.nightly-2018-06-27
Commit Hash: 0e3c1fc
```
Blocks #1006

**Comment by nehashri** [comment]
@sguptatw This was done intentionally. Special parameters inside table will be supported **only** for inline tables since it will be following Gauge specified syntax.
A CSV file doesn't follow any Gauge syntax and we should not be changing its behaviour. A CSV file may contain any data and Gauge should not attempt to interpret its data.
