### ISSUE TITLE
Gauge.Properties file gets malformed after several parallel cmd executions

### ISSUE THREAD

**Issue by s0ren1** [getgauge/gauge#1122]
### Expected behavior
gauge.properties file should have no modifications after execution

### Actual behavior
gauge.properties file has some variables or values malformed (find some values in incorrect variables for example)

### Steps to reproduce
1. Execute 10 concurrent command lines starting with "gauge run" with no parallel command.
2. Wait for all of the tests to finish
3. Some test fail with kill plugin timeout issues
4. Review gauge.properties file to find the values malformed

###
I believe that the c# plugin modifies the gauge.properties file which I think it should not. Although I'm not quite sure

### Gauge version
```
Gauge version: 1.0.0
```

**Comment by sriv** [comment]
> I believe that the c# plugin modifies the gauge.properties file which I think it should not. Although I'm not quite sure

I don't think so. Gauge tries to write the `gauge.properties` with defaults if it does not already have the property set. Ex. when gauge introduced a new property, and it needs to be in `gauge.properties`.

The problem is in the implementation, gauge holds a map of property name/value and loops through it to write to file. 

Iterating through a map in `golang` does not guarantee an order, so even if you run gauge consecutively for a number of times, the `gauge.properties`'s property order gets jumbled.

I am however surprised to hear that concurrent runs are messing up the file, since `gauge` [tries to acquire](https://github.com/getgauge/gauge/blob/master/config/properties.go#L171) an exclusive lock to the `gauge.properties`, so ideally only one process should be writing the file.

Could you please share:

- which OS have you noted this on?
- a sample of how the bad `gauge.properties` looks like?

**Comment by s0ren1** [comment]
@sriv the server is... OS version: Microsoft Windows NT 10.0.14393.0
as for the malformed file.. I kinda replace the values immediately because is my prod environment, but according to a screen shot from a fellow automation tester, he found this malformation in the gauge.properties file:
`plugin_kill_timeout = 3lliseconds for requests from the language runner.`

**Comment by s0ren1** [comment]
@sriv we made gauge.properties as a read only file. So far, our big chunk of tests is running fine. I think that you guys should investigate the issue anyway. If I find any other issues, I will let you know.

**Comment by sriv** [comment]
Fix should be available in nightly >= 01-08-18
