### ISSUE TITLE
Syntax highlight of multi-line text should be handled

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#1140]
**Expected behavior**
The diagnostics of unimplemented step should highlight the step spanning across multiple lines

**Current behavior**
The diagnostics of unimplemented steps show only the first line

Child of https://github.com/getgauge/gauge/issues/265

**Comment by sriv** [comment]
Assuming that this feature will be available only on LSP clients.

**Comment by sriv** [comment]
## Dev Notes

The main cause of this issue is that while parsing Gauge does not hold the fact that the step spawns across multiple lines. https://github.com/getgauge/gauge/blob/master/parser/lex.go#L133

Due to this loss of information, LSP is unable to determine the span of the step text that is in multiple lines. Hence the diagnostics are restricted to the first line.

To fix this, the parser needs to be changed to lex and parse multi line step text. And this would change the parser to now start looking ahead.

**Comment by Debashis9012** [comment]
All the requirements have been tested and verified.
Tested version: `gauge: e093fe2 `
