### ISSUE TITLE
Proposal add some context of command for before suite

### ISSUE THREAD

**Issue by olejkavn** [getgauge/gauge#1141]
Proposal to add some commands for gauge to get sush info, it could be somethins like:
gauge get [specs, tags, etc] by [specs, tags]
for me example: gauge get --tags by tagA

Or it can be added in some global test context

Usage of this feature in my case, it's dynamic creation of test run from test:
I deploy feature A and wan't to run test by tagA and create run with my cases in my Test Managment System in @BeforeSuite

**Comment by Apoorva-GA** [comment]
@olejkavn Could you give us an example with the spec file with tags and implementation file.
This will help us understand your use case better.

**Comment by ajoecker** [comment]
personally I see too much interweaving of responsibilities here.

it seems that you like to have Gauge/your implementation doing the complete cycle of controlling your TMS and your automated tests. 
I would strongly advice against that and keep things separate.

Assuming I understood your use case, it is better in my eyes to have a script that will handle the orchestration and creates the run and the triggers Gauge.

**Comment by olejkavn** [comment]
@Apoorva-GA can't understand how it would help you, it 's not depend on specs and their implementations

**Comment by olejkavn** [comment]
@ajoecker Yeap, I understand this. But in case if this stuff would do some script or something else we should support one more mapping, now mapping between TMS case-id and tests(spec files) stored only in gauge tags. We could implement some mechanism for parsing of spec files, but gauge already do it, and some extending of this logic would be nice for us.

**Comment by ajoecker** [comment]
@olejkavn I understand the problem you have, that is way, I created https://github.com/ajoecker/gauge-testrail, my scenarios have a Gauge tag corresponding to TestRail case id.

I am not sure I understand , what you mean with _"should support one more mapping, now mapping between TMS case-id and tests(spec files)"_ - this quite vague. And as said, I would vote against any hard-wiring of gauge and a TMS.

I also think "give me all tags for tag x" is confusing, I guess you mean, give me all case ids of scenarios, which have also tag x in comon ? because a generic "give me all tags", would not return just the caseid, also - in your example - _serviceB_

Gauge has the `list` command (see https://github.com/getgauge/gauge/issues/1007), there was discussion to enhance that to have a more verbose output. This might help you, to retrieve all scenarios/tags for a certain input - but it would still require to parse stuff on your side.

**Comment by olejkavn** [comment]
@ajoecker 

> And as said, I would vote against any hard-wiring of gauge and a TMS.

please check previous comment. there are no any hard-wiring

>  would not return just the caseid, also - in your example - serviceB

correct, I'm already fix it in comment, thanks. Anyway parsing of this list it's task for my script that should run tests

**Comment by olejkavn** [comment]
@ajoecker 
all that i need it's get all tags that placed in one spec/scenario with serviceA tag, thats all. I don't need any scenarios/specs etc.
check point 2 in https://github.com/getgauge/gauge/issues/1141#issuecomment-411725365

and yes it can't be enchanced **_list_** command like: gauge list --tags [tagNames]

in my case:
>CI trigger gauge command "give me all tags for tag serviceA"
list of specs: spec1(tags: serviceA, serviceB, caseid1), spec2(tags: serviceA, serviceB, caseid2), spec3(tags: serviceB, caseid3), spec4(tags: serviceA, caseid4)
this command should return this list: [serviceA, serviceB, caseid1, caseid2, caseid4]

gauge list --tags specA 
return [serviceA, serviceB, caseid1, caseid2, caseid4]

**Comment by ajoecker** [comment]
@olejkavn thanks for the explanation.

We might need to find a more understandable/intuitiv syntax than `gauge list --tags specA`, but I think the use case is now understandable

**Comment by olejkavn** [comment]
@Apoorva-GA  any updates?

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
