### ISSUE TITLE
Introduce a pause method

### ISSUE THREAD

**Issue by ajoecker** [getgauge/gauge#1165]
Based on the discussion of https://github.com/getgauge/gauge-java/issues/178, I think it would be benefical to introduce an API method like `Gauge.pause()`, that expects a key press to continue.

As different runners have different solutions for this and even for a single runner, there exists multiple solutions, it would be easier and more maintainable to bundle this inside an API method.

**Comment by patmuk** [comment]
In order to have CI ignoring waiting for an user input we could have two approaches:
1. Configure CI to not run the scenario with includes a pause (manually). This works today, though I believe it is not a perfect solution. A user would have to have a dedicates "demo" scenario which might be a 1:1 copy of a test scenario.
2. extend the environment specific settings to have a flag "ignore 'pauses'", which just continues an a pause step.

**Comment by zabil** [comment]
Use cases for pausing execution

* Filling up captchas 
* Entering up OTP's

Assuming that these actions are manual. 
On CI environments there must be an option to ignore pauses. Or Ignore pauses by default and accept a command line parameter to activate the pauses.

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
