### ISSUE TITLE
Install via language package manager

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#1180]
### Expected behavior
should be able to install gauge binary using the package managers used in various language stack:

- [ ] maven (java)
- [ ] gradle (java)
- [ ] rubygems (ruby)
- [x] pip (python)
- [ ] nuget (C#)

Note: #1157 allows gauge to be installed via npm/yarn. This meta issue is to roll this out to other languages.

### Actual behavior
Gauge can only be installed via 
- standalone installer
- download and extract a zip archive
- OS package managers such as dep/rpm/homebrew/chocolatey

This breaks the dependency of a gauge project, by mandating gauge installation as a pre-requisite.

This also does not aid in reproducible run, since the project's run cannot be locked down to a version of gauge.

### Steps to reproduce
N/A

### Gauge version
```
v1.0.1
```

**Comment by BugDiver** [comment]
@surevs For command line tools, `entry_point` in `setup.py` is used to specify the `console_scripts`.
https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html

`pip install <package>` copies the specified scripts into to `/usr/local/bin` (*nix) and `C:\Pytohn\Scripts` (windwos).
In case of local install with `pip install <packafe> --user` the scripts are copied to `$USER/.local/bin`.

We should follow the same convention instead of copying to diff location, so . that we don't need to worry about PATH and all.

@sriv ??

**Comment by surevs** [comment]
@sriv and @BugDiver sorry about the little delay in response, Done with setup.py script. please review and let me know for any further changes needed.

**Comment by BugDiver** [comment]
The PR for pip installers has been merged. Still, we need to create a PyPi package for it on `https://pypi.org/` and add scripts to automate publish.

**Comment by zabil** [comment]
Closing this. For maven and gradle this cannot be done by just including a plugin reference as the Gauge executable is platform dependent.

Other libraries like https://github.com/bonigarcia/webdrivermanager#webdrivermanager-as-java-dependency get over this by calling a `setup` method in the tests. Gauge does not want to use a `setup` method as versioning and updates will not be easy to manage.
