### ISSUE TITLE
Support for custom validation function.

### ISSUE THREAD

**Issue by gnk1gsr** [getgauge/gauge#1246]
Currently the gauge validation function does check only on two things before skipping the spec.
1> duplicate step implementation
2> step implementation missing all together. 

Felt it would be great if we could have support for custom validation function. 
Well, I tried to circumvent this by adding validation steps in [BeforeSuite] , but that didn't skip my test suite execution upon validation failure, since its only the initialization routine stub. So even if initialization fails, Gauge doesn't seem to care about it and continues to run scenarios. 
I feel provision for custom validation function would be nice to have. 

Opening this  for further discussion after quick chat with @sriv on gitter.

**Comment by nehashri** [comment]
This seems like a good feature to have. 
For info, these steps must considered while implementing this. 
The validation in this case must be made in between the Validation and execution phase. This is because in case of some runners, during validation phase the implementation files are not loaded, they are just parsed to find the validation errors. So this would mean that we need to start the runner after validation phase, then do the custom validation.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
