### ISSUE TITLE
make data table execution context available to user for pushing results totest case management via API

### ISSUE THREAD

**Issue by mschreiber16** [getgauge/gauge#1282]
Need a way to get the current row and column (data) through execution context.    Need to use this information for pushing test results to a test case management system that supports data tables. 
-->

### Expected behavior
Some type of hook in the step execution context that will enable the user to  obtain information regarding header, row, column, etc of a Gauge data table.  This will be used to push test results to a test case management app that supports data tables in the test cycles. 

Example Data table contents:
5 rows, 3 columns
Example from Test Cycle that utilizes a  data table:
Test case with 5 steps.  Step 3 and 5 utilize the data table
Test Cycle will be structured in such that there are 5 sets of steps.  One set for each row in data table 
Test Results will be pushed to each step of each row iteration

Gauge would know what step it is on as well as the current data table column, row, and header.

### Actual behavior
Nothing available to user for data table attributes in the execution content

### Gauge version
1.0.0

**Comment by sriv** [comment]
### Dev notes

Since this involves enhancing the data that's passed between gauge and the runners, I believe the following steps can help:

Step 1 -
https://github.com/getgauge/gauge-proto/blob/257028a18851f30139367152e32a983a53f94b96/messages.proto#L120

The `ExecutionInfo` struct gets passed to the runners at relevant lifecycle. You may notice that it contans some data already. Feel free to add fields/structs that can hold this additional data. Be sure to mark them as optional, else it will break backward compatibility.

Step 2 -
Once you are happy with the data model above, clone https://github.com/getgauge/gauge, update the submodule `gauge-proto` to include the changes above.

Run [`./genproto.sh`](https://github.com/getgauge/gauge/blob/master/genproto.sh) This would propogate your changes to the golang stub.

Step 3 -

The issue mentions having this information at the step level, I recommend having it under a scenario instead, since all steps under the scenario will have the same table details. But feel free to duplicate this infomation to steps, if that makes it easier to use.

if you decide to propogate this at step level, then you need to set this in https://github.com/getgauge/gauge/blob/be614440395760f919a57399c79b3073124ba613/execution/stepExecutor.go#L28

Step 4 -

pulling this information - the `scenario` struct is populated with the current table row (note that the table rows can be from a spec datatable, or a scenario data table) - https://github.com/getgauge/gauge/blob/be614440395760f919a57399c79b3073124ba613/gauge/scenario.go#L20-L23

The above need to be propogated to the step (not required if this information is sufficient at scenario hooks)

Step 5 -

Update the runners' proto stubs to include the newly added fields.

I think the above should be a decent start, and once you have all these in place, you should see this information coming up as part of `ExecutionInfo` in the runners' hooks.

---

I hope this helps anybody interested in picking this up.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
