### ISSUE TITLE
Feature Request: WDIO-Gauge-Service

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/gauge#1369]
Currently, gauge does not give access to run WDIO-CLI(WebdriverIO) using wdio.config.js. The only way right now is by using the WDIO client, which does not give the flexibility to use any of the services.

https://github.com/webdriverio/webdriverio/tree/master/packages

It would great if we can build a wdio-gauge-service similar to jasmine framework adapter or Cucumber framework adapter for WDIO v5.

Gauge service helps in plugin access for WDIO through wdio.config.js instead of the standalone way (client way) of utilizing/executing WDIO scripts through the gauge.

Helps in utilizing existing services plugin for WDIO like browser stack, sauce, CDP service etc without reinventing the wheel
Greater utilization of best of both in case of service plugins, data handling capabilities of gauge, documentation features of gauge, etc

Note: All the services available in WDIO v5 are designed keeping WDIO CLI in mind having it as a peer dependency for each service.

Co-authored-by: @SrinivasanTarget

**Comment by SrinivasanTarget** [comment]
@zabil  ping

**Comment by nehashri** [comment]
For a WDIO plugin, we will have to create a new wrapper around gauge-js. This will be installed as a runner in Gauge. The WDIO runner plugin will have a script to run the WDIO on start. This plugin will also have to wrap around steps and hooks so that all global variables that are made available by WDIO (like browser) will be available for all steps to use by default.

This will let users run the tests on local or BrowserStack or Sauce etc., WDIO plugins will handle this.
We will be able to piggyback on WDIO’s reporter plugins like JUnit, testrail, etc. The WDIO gauge runner plugin will have to emit some events to enable this.

Users will not be able to run Gauge through `wdio` command, they will have to rely on Gauge to start the service.
Some options in `wdio` like `—spec` cannot be specified with WDIO Gauge runner plugin.
Other options can be made configurable.

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
