### ISSUE TITLE
Feature Request: environment dependent variables in step parameters

### ISSUE THREAD

**Issue by tobias-lehmann-aperto** [getgauge/gauge#1395]
Currently, Gauge supports environment specific properties on the step implementation side.
For my project I am looking for a way to use placeholders also in the spec definition.
I am thinking of something like this:

`table:${env}/params.csv`

Or this:

`* open page "https://${domain}/home.html"`

It would empower our testers, and make the steps more explicit in many cases because some parameters should not be hidden behind the implementation.
The alternative would be to "build" the spec file for the respective environment, which I would like to avoid.

Thank you for considering

**Comment by zabil** [comment]
This will help solve https://github.com/getgauge/gauge/issues/1083

**Comment by alpha1592** [comment]
I second this request!!
I also require this functionality. In fact, i was about to raise a feature request for this. 
We keep our test data under env/some-env/data which is environment specific data. its hard to create dynamic specs which references the data files without hard coding an environment like default. 
i would like to be able to do the exact thing as proposed in the description where we specify the env as a placeholder in the spec which gets injected with the actual runtime env passed in thru `-e=xyz`. 

``` 
* This is a step with data <file:/env/${env}/data/mydata.csv> 
```
Thanks

**Comment by ajoecker** [comment]
but cannot you not use the path to the data in the env/some-env/user.properties and then not define it in the step, but simply load it in the implementation ?

as a tester i would rather read

`* open webpage`

rather than

`* open page "https://${domain}/home.html"`

the first is way more intuitiv and readable

**Comment by tobias-lehmann-aperto** [comment]
We have a step implementation library for a set of different projects. Our testers are happy, because they can reuse many parts.
At the moment placeholders in some steps' parameters are replaced in that library, but it would be much better to have it globally.

**Comment by vinodbhardwaj1** [comment]
We are also loading  "table:src/testdata/test.csv" at scenario level rather than step level. Kindly implemented this feature so we can load environment based csv file.

**Comment by zabil** [comment]
Unfortunately file contents are required while parsing the spec files to check for parameters, so Gauge cannot support loading the cdv's dynamically. 

The workaround to this is to generate csv per environment outside gauge and then run the Gauge specs.
Also gauge will not be adding environment variable syntax to it's specs.

**Comment by sergueis** [comment]
I support this feature.
Suppose, We have this step:
  * Enter <text> into current web-element

Sometimes, I want to use it like this:
  * Enter "Hello" into current web-element

But sometimes, I want to enter variable name instead of explicit text, or even combine them, like:
  * Enter "Hello ${username}" into current web-element
 
NB. **username** var is not only env-dependent but also changes form run to run, so it's impossible hard-code it into env.properties files.
