### ISSUE TITLE
option to stop execution if a test fails

### ISSUE THREAD

**Issue by djpnewton** [getgauge/gauge#1467]
I cant see how to do this

it is very useful if you just want to focus on the failed test and maybe inspect state

**Comment by Apoorva-GA** [comment]
@djpnewton  If execution of a step fails, that step is marked as failed and execution of further steps in the scenario will be skipped and the execution of the next scenario begins. This is done because we encourage scenarios to be independent of each other.

However there is a way to run only failed scenarios using command `gauge run --failed` this runs only the scenarios failed in previous run. Also note that this cannot be used in conjunction with any other argument.

**Comment by nehashri** [comment]
@djpnewton If I understand, you want to "pause" not "stop" the execution in order to inspect the state of your test during execution.
To inspect the state, you may want to try debugging that test with the help of an IDE like VSCode or IntelliJ. We have Gauge plugins for the IDEs which help you to do that.
