### ISSUE TITLE
AfterScenario is executed after TearDown step

### ISSUE THREAD

**Issue by fefferico** [getgauge/gauge#1482]
### Expected behavior
**AfterScenario** step should be executed **before** the **TearDown** step
https://github.com/getgauge/gauge-js/blob/master/docs/syntax/execution-hooks.md

### Actual behavior
**AfterScenario** step is executed **after** the **TearDown** step

### Steps to reproduce
**`step_implementation.js`**

```
/* globals gauge*/
"use strict";
const { openBrowser,write, closeBrowser, goto, press, text, focus, textBox, toRightOf } = require('taiko');
const assert = require("assert");
const headless = process.env.headless_chrome.toLowerCase() === 'true';

var stepCount=1;

beforeSuite(async () => {
    await openBrowser({ headless: headless })
});

afterSuite(async () => {
    await closeBrowser();
});

step("Goto getgauge github page", async () => {
    await goto('https://github.com/getgauge');
});

step("Search for <query>", async (query) => {
    await focus(textBox(toRightOf('Pricing')))
    await write(query);
    await press('Enter');
});

step("Page contains <content>", async (content) => {
    assert.ok(await text(content).exists());
});

afterStep(async () => {
    console.log('After Step: ' + (stepCount++));
});

afterScenario(async () => {
    console.log('after scenario');
});

step("The end", async () => {
    console.log('Tear down step');
});
```

**`example.spec`**
```
# Getting Started with Gauge

This is an executable specification file. This file follows markdown syntax. Every heading in this file denotes a scenario. Every bulleted point denotes a step.
To execute this specification, use
	npm test

## Search Taiko Repository

* Goto getgauge github page
* Search for "Taiko"
* Page contains "getgauge/taiko"

___
* The end
```
### Gauge version
```
Gauge version: 1.0.5

Plugins
-------
html-report (4.0.8)
js (2.3.5)
screenshot (0.0.1)
```

**Comment by shubhamsc** [comment]
@fefferico Context and Tear Down steps are also a part of a scenario in a spec file.
Context steps will execute before executing any steps of the scenario.
Same, TearDown steps will execute after completing all steps of the scenario.

BeforeScenario and AfterScenario are the hooks which execute even before starting any step of a scenario/after complete all steps of the scenario.
Executing AfterScenario after tearDown step is expected behaviour. Please see the [docs](https://docs.gauge.org/writing-specifications.html#tear-down-steps) for more details.
