### ISSUE TITLE
[Improvement] Allow local scenarios to be accessed as a step from the same spec file

### ISSUE THREAD

**Issue by sarut0bi** [getgauge/gauge#1512]
This is an improvement request

### Expected behavior
Allow local scenarios to be accessed as a step from the same spec file.
Unlike CPT we don't want this scenario to be exposed to all other specs.
Same result could be done with working with a CPT file but i think we will keep readability up that way.

### Example
```
# test spec
## ScenarioA
* Do A
## ScenarioAB
* Do A
* Do B
```
=>
```
# test spec improved
## ScenarioA
* Do A
## ScenarioAB
* ScenarioA
* Do B
```

**Comment by nehashri** [comment]
@sarut0bi This would compromise on the readability of the specs. Concepts exists so that a set of steps can be reused. I don't see any reason why a concept should be used only within a certain spec file. 
A step can be used in any spec. A concept similarly can be used in any spec. Limiting its scope would cause confusion. Similarly, reusing a scenario would make a scenario confusing to use and change its definition. Due the the nature of the change, and change in definition of scenario, we will not be able to implement this feature.
