### ISSUE TITLE
Format of dates, times and currencies start configuration missing in documentation

### ISSUE THREAD

**Issue by marcelmokos** [getgauge/gauge#1637]
When we run tests with on our computers with European region configs. Tests are failing due to differences with the date and time formats.

We are missing an option to set up timezone and regional config in gauge to everyone in our team will have the same regional config and timezone.

**Comment by fhavrlent** [comment]
One more info, it fails only when tests are running in headless browser.

**Comment by sriv** [comment]
Timezone and format are usually set either by the operating system (locales) or if you use any sort of internationalization.

In test code, you could use UTC time instead of local time, and offset it when required. Or in the OS, set the timezone (ex. `timedatectl set-timezone <timezone>` in linux based systems).

Gauge does not manage either, presently. What sort of configuration would you like here? Perhaps if you can illustrate with an example, it'll be help in understanding this better.

**Comment by sriv** [comment]
> One more info, it fails only when tests are running in headless browser.

@fhavrlent - what browser/driver are you using? Is there any sample that you can share please?

**Comment by zabil** [comment]
Can someone share some sample code or example how this fails? Like @sriv mentioned this can be set in code. You can also use [environments](https://docs.gauge.org/configuration.html?os=macos&language=javascript&ide=vscode#using-environments-in-a-gauge-project) to store and use the time zones.

**Comment by fhavrlent** [comment]
This runs in Chrome, using Selenium. 
We have a date, 1980-04-17 for example, that is in year-month-day format. When I run tests in headless, it seems to be using different input format, so I end up with 12/04/1980 (month/day/year) -> it fixes 17 to 12. When I run it with the normal browser, date inputs are correct, so this one would give me 04/17/1980.

**Comment by zabil** [comment]
>  it seems to be using different input format, 

Unfortunately, handling dates are hard so it's best that the tests be deliberate about the date formats by using Date libraries provided by the language or using external libraries written for this specific purpose like [Joda time](https://www.joda.org/joda-time/) or [moment js](https://momentjs.com)
