### ISSUE TITLE
Refactor command missing

### ISSUE THREAD

**Issue by DvagNic** [getgauge/gauge#1706]
### Describe the bug

There is no refactor command available.

### What command(s) did you run when you found the bug?

For e.g. 
```
# gauge refactor "bla" "bleu"
Error: unknown command "refactor" for "gauge"
```

### Versions
1.1.1 (homebrew Mac)

#### Gauge (Output of `gauge -v`)
```
# gauge -v
Gauge version: 1.1.1
Plugins
-------
html-report (4.0.12)
python (0.3.10)
screenshot (0.0.1)
```

#### Operating System information
macOS Catalina 10.15.5

**Comment by sriv** [comment]
hi @DvagNic - The command line refactoring was removed as part of https://github.com/getgauge/gauge/commit/3abcc41d84415db07c5ad90820e3d8e16dd2e433. We felt it was unused since the IDE refactoring was what we learnt being used most.

If it's ok with you, could you share some more about your workflow/setup and how the command line refactoring helps? We'd be happy to put it back in.

Apologies if this has messed up things for you!

**Comment by DvagNic** [comment]
Hi, no problem. I was just wondering because the removal is not reflected in the docs. I don't need that feature and could have used the Visual Studio Code refactoring.

**Comment by sriv** [comment]
Where do you see the reference in docs? We might have missed something.

**Comment by DvagNic** [comment]
This one:
[https://docs.gauge.org/writing-specifications.html?os=macos&language=python&ide=vscode#refactoring-gauge-refactor](https://docs.gauge.org/writing-specifications.html?os=macos&language=python&ide=vscode#refactoring-gauge-refactor)
