### ISSUE TITLE
how we can run test in parallel using gauge for selenium cross browser testing using js ?

### ISSUE THREAD

**Issue by 1160545** [getgauge/gauge#1708]
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.12)
js (2.3.12)
screenshot (0.0.1)

ChromeDriver 84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310})
geckodriver 0.26.0 (e9783a644016 2019-10-10 13:38 +0000)

I have enabled multithreading true in gauge default but gettting "runner doesn't support multithreading, using multiprocess parallel execution in gauge." error   while running gauge run --parallel spec

**Comment by BugDiver** [comment]
@1160545 

> runner doesn't support multithreading, using multiprocess parallel execution in gauge." 

Guage Javascript plugin does not support multithreading execution, that's why you seeing this warning. It's not an error and does not stop the execution. The parallel execution will happen using a multi-process of the runner.
Are you facing some error in running the project? In that case please tell the exact issue

**Comment by 1160545** [comment]
I am not facing any error in running of project
But could please guide me how we can perform parallel execution in gauge using multi-process for js plugin ?

**Comment by zabil** [comment]
Please refer https://docs.gauge.org/execution.html?#parallel-execution
