### ISSUE TITLE
gauge deploy solution

### ISSUE THREAD

**Issue by roughsoft** [getgauge/gauge#1743]
I have tree machine，one I setup gauge，the other two I setup gauge-js runner，Can I get the gauge grid？

**Comment by zabil** [comment]
This setup is not supported.

**Comment by roughsoft** [comment]
@zabil ，js runner can run in thread？

**Comment by zabil** [comment]
You can run tests is parallel using the https://docs.gauge.org/execution.html?os=macos&language=javascript&ide=vscode#parallel-execution feature. However, please note JavaScript(that language and runtime) does support multi-threading.

**Comment by sriv** [comment]
@roughsoft in the present architecture, gauge and the runner are independent processes, and they expect to be in the same machine. 

There are examples of using gauge+runner in one machine, but the test code orchestrating a remote grid (saucelabs/browserstack), so perhaps you can use a similar setup to achieve your goal.

**Comment by roughsoft** [comment]
@zabil @sriv ,thank you!
I have 1000 specs and 3000 Scenarios.
I want to use selenoid.
I setup gauge on one machine ,this machine run the js runner, if I start 200 browser instances in my solenoid ,
the gauge must run 200 processes, because gauge  does not support multi-threading.
I think the machine is not ok, if it is 200 threads, the machine is ok.

**Comment by zabil** [comment]
In response to https://github.com/getgauge/gauge-js/issues/388#issuecomment-689513492

> communication between gauge and language runner is through gRPC ,we know gRPC support deployment server and client crossing the two machines, so why not refactor the runner code connecting the remote gauge by url

Gauge will not support a remote runners, grid based runner or load distribution to nodes. It is designed to be a lightweight runner that can be run on the local machine, ci machines as well as well as within IDE's and will remain that way.

Like @sriv mentioned for your requirement please use selenium grid, browserstack or saucelabs. Browserstack supports Gauge https://www.browserstack.com/docs/automate/selenium/getting-started/java/gauge

**Comment by sriv** [comment]
Some further notes:

- Technical changes will include more than exposing the endpoint:
  - gauge and the runner do not have a handshake since the runner is brought up by gauge as a subprocess. In a distributed setup, there needs to be a handshake in place
  - gauge and the runner write to the same log. log aggregation will be an additional burden.
- gauge and the runner share state using filesystem. Both gauge and gauge-js scan the project directory for different purposes. Keeping filesystem in sync between machines is error prone.

All of the above is possible (we did [an experiment a few years ago](https://github.com/getgauge/gauge-docker-java) to put the runner in another machine, using docker).

As @zabil says, it's better to use a tool designed to do distributed machine workflow orchestration to scale. This could mean using a CI/CD tool like [GoCD](https://gocd.org) or you could use tools such as [ClusterRunner](https://www.clusterrunner.com/) or [TestLoadBalancer](https://test-load-balancer.github.io/) (unmaintained).

**Comment by roughsoft** [comment]
yeah!thank you very much!
