### ISSUE TITLE
Data driven execution from sql datasource or rest api data source

### ISSUE THREAD

**Issue by roughsoft** [getgauge/gauge#1745]
Data driven execution is great feature.
I want to use datasource from database or rest api to my table.
How can I get it?
@zabil

**Comment by roughsoft** [comment]
I want to make gauge-datasource plug-in.
But I do not know where can I start.

**Comment by zabil** [comment]
@roughsoft since these are questions it is better to discuss these at https://spectrum.chat/gauge?tab=posts
Github is usually used to track development and report bugs. 

That said. There is a discussion about datasource here https://github.com/getgauge/gauge/issues/1242
It is best to avoid connecting to external datasources as they make the tests unportable and non deterministic. You can instead export data to csv and run the Gauge tests.
