### ISSUE TITLE
Help required attaching the HTML report to Azure CI pipeline , do we have any plugin to attach complete report 

### ISSUE THREAD

**Issue by hcsan** [getgauge/gauge#1749]
Hi Team,

I have  read the  gauge documents . look like XML report will not contain each details of steps. Need to understand the best way to publish the HTML report with screenshots on the azure dashboard. 

https://docs.gauge.org/howto/ci_cd/azure.html?os=windows&language=java&ide=vscode

i used the HTML plugin but it only attaches index.html.

Please let me know the configurations.

Thanks
Shc

**Comment by hcsan** [comment]
This with Selenium with Java 

Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.8)
java (0.7.9)
python (0.3.7)
screenshot (0.0.1)
xml-report (0.2.2)

**Comment by sriv** [comment]
html report is generated in $PROJECT_ROOT/reports (by default). You can customize this by setting `gauge_reports_dir` property.

The reports generated consist of various files (html as well as assets). It's best that you upload and serve them in the same structure. Please see [Azure's documentation](https://docs.microsoft.com/en-us/azure/devops/artifacts/?view=azure-devops) and choose an approach best suited for your use case.

Closing this, since there isn't anything that Gauge/html-report can do here.
