### ISSUE TITLE
Feature suggestion: add support for numbered lists for steps (versus unordered list)

### ISSUE THREAD

**Issue by CharlieDigital** [getgauge/gauge#1764]
**Use Case**
Allow numbered lists as an alternative to unordered bullet lists for step declaration within the specifications.

**Reasoning**
One of the big draws of Gauge is the markdown based format which enhances reuse of the test cases as "living documentation". For software validation, I find this extremely powerful as we can create the specification and potentially the final documentation from the same markdown.  The specification itself could be published and be fully encapsulated.

My thought, however, is that this would be even better with the option of using numbered steps rather than the unordered lists. 

The numbers would have no actual effect on order of execution and would be arbitrary. The main benefits are two fold:

First is that it allows improved communication between the teams writing the tests and the teams writing the software being tested. It allows referencing specific steps of specifications by number and makes it easier to communicate about the design of the Gauge test cases. "The test is breaking at step 17 of the change password scenario".  Without a step number or some convention of identifying steps in shorthand, it can be quite verbose to communicate between teams for large scenarios.

Second is that it can also aid in identifying errors by providing a numbered identifier.

**Comment by sriv** [comment]
Thanks for bringing this up, and the detailed reasoning.

some options:

As you've stated, gauge's execution of steps is in the order of definition, so in essence the steps have an implicit index, which isn't exposed in the reports (console/html or others).

So, the simple option would be to make the step index (1 based) explicit in the reports. 

The above will not solve the authoring problem, since the spec files would still consist of unordered lists.

The below would add to the complexity:

- Context and Teardown steps are inlined during execution, whereas at authoring time, these are out of scenarios. As a result, the step no. 1 in the scenario is really `(num of context steps) + 1`. This is tricky to realize in the spec files.

- Gauge allows steps to be defined in a concept (which can be nested within another concept). This is more complex than context and teardown, since concepts exist in different files!

If you are happy with the html report showing step line number, that can be easily achieved in [the template](https://github.com/getgauge/html-report/blob/6fca41850fee3fb83d57bd6b11b1aed2af7413a5/themes/default/views/partials.tmpl#L505).

Note - you can customize html-themes yourselves.

**Comment by zabil** [comment]
@CharlieDigital closing this issue for now because of the challenges mentioned 👆

**Comment by CharlieDigital** [comment]
Understood :)

We are internally still debating adoption so no progress on our side though there is interest in implementing this.
