### ISSUE TITLE
add support for delay interval between retries.

### ISSUE THREAD

**Issue by hdw868** [getgauge/gauge#1778]
In this [PR](https://github.com/getgauge/gauge/pull/1370), we add support for retry failed cases, but one thing we found missing is the delay interval between each retry. This could be very useful when some test is failed due to some resource limit, such as DB connection limit and etc. Therefore, could we add a flag let's say  `--reruns-delay` to set delay interval between each retry. We may refer to https://github.com/pytest-dev/pytest-rerunfailures for preference.

**Comment by zabil** [comment]
@hdw868 Thanks for looking at this and suggesting the feature. 

Flaky tests are a frustrating. Gauge takes a conservative approach by limiting re-run features so that the actual test environment is fixed. 

In the interest of keeping it as simple as possible Gauge won't be implementing this feature :(
