### ISSUE TITLE
Allow variables to be declared for each .spec file & resolve Variables integrated in a path

### ISSUE THREAD

**Issue by aWdas** [getgauge/gauge#178]
It would be wonderful to be able to set variables for a specific test suite without having to create a one-line .csv-file for every Test-Suite. Furthermore, variables should still be resolved if they are combined with other information, e.g. in a file-path. Together, this would look something like this:
# Spec

test_dir = c:\user\bob\test\
## Test 1

*Create file in "<test_dir>\files\"
*Create another file in "<test_dir>\other_files\"

**Comment by hakito** [comment]
As an alternatve to the nesting of the variable within another variable could be that the argument for a step must be a (quoted or unquoted) string surrounded by whitespace.

For example the following could be considered as equivalent:

`* Create file in <test_dir>\files\`
`* Create file in <test_dir>"\files\"`

And should expand to `c:\user\bob\test\\files\` when passed as argument to the step. In fact I think resolving a var within a string is a not so good idea because we would have to quote the `<` and `>` chars.

For example:

`* Create file in "<test_dir>\files\"`

Shoule expand to `"<test_dir>\files\"` when passed as argument to step. As explained at the beginning I'd suggest to use whitespace to separate arguments.

For example:

`* The name of the victim is "Mr. John" "Doe"`
`* The name of the victim is "Mr. John" Doe`

Should expand to two arguments `Mr. John` and `Doe`. But

`* The name of the treating doctor is "Dr. "Dolittle`
`* The name of the treating doctor is "Dr. Dolittle"`

should expand to only one argument `Dr. Dolittle`

**Comment by zabil** [comment]
Gauge won't be implementing this to keep the spec format simple.
