### ISSUE TITLE
Gauge executables should be signed

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#190]
Currently, the gauge executables and installers shipped are not signed, and this could be on reason why some Antivirus flag these.

Exes to sign:

- [x] Gauge.exe
- [x] Gauge_screenshot.exe
- [x] Gauge.CSharp.Runner.exe
- [x] Gauge-java.exe
- [x] Gauge Windows installers (x86 and x86_64) 
- [x] Gauge Mac installers (x86 and x86_64)
- [x] Linux distros (.deb and .rpm)

**Comment by Thunderforge** [comment]
The installers aren't signed either:

 - gauge-0.1.7-windows.x86.exe
 - gauge-0.1.7-windows.x86_64.exe
 - gauge-0.1.7-darwin.x86.pkg
 - gauge-0.1.7-darwin.x86_64.pkg

We just ran into a problem where we were unable to install on one of our developer's systems because they were not permitted to install unsigned software. We were able to make an exception this time, but future versions will need to be signed or we won't be able to update.

**Comment by deepthigc** [comment]
@Thunderforge We now have a new release of Gauge which has signed installers(except for Mac). Please let us know if you see the warning on installing this? We expect that it will work without any warnings.

**Comment by Thunderforge** [comment]
I believe that Gauge 0.1.8 was also signed. Regardless, we are not having any issues with the signed Windows installers. We still would like to have signed Mac installers though.

**Comment by kaustavdm** [comment]
Tested with artefacts from latest builds for Windows and OSX.
