### ISSUE TITLE
Unable to build gauge, cannot find package "github.com/getgauge/gauge/version"

### ISSUE THREAD

**Issue by teknologika** [getgauge/gauge#192]
Grabbing the latest version of gauge from github and issuing the command

     go run build/make.go

In the gage directory fails with the error ...

    build/make.go:24:2: cannot find package "github.com/getgauge/gauge/version" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/getgauge/gauge/version (from $GOROOT)
	/Users/bruce/github/teknologika/gocode/src/github.com/getgauge/gauge/version (from $GOPATH)

Am I missing something obvious or is that a private repo ?

**Comment by mahendrakariya** [comment]
If you have just git cloned the gauge repo, it would not have downloaded all the dependencies required by gauge. Ideally, we recommend to run `go get github.com/getgauge/gauge`. This clones the gauge repo along with all the required dependencies and builds it.

However, since you have already cloned the repo, you can run `godep restore`, which will download and build the dependencies.

**Troubleshooting:**
  * Ensure there is [version](https://github.com/getgauge/gauge/tree/master/version) folder in the cloned repo with 3 files validation.go, version.go and version_test.go
  * If you don't have `godep` installed, run `go get github.com/tools/godep`
  * Ensure `GOPATH` env variable is set and `$GOPATH/bin` is in `PATH`

**Comment by teknologika** [comment]
I knew it was me :-)

**Comment by mahendrakariya** [comment]
Glad it worked for you :)
