### ISSUE TITLE
[bug] gauge 1.3.1 failed to install plugin on apple silicon

### ISSUE THREAD

**Issue by chenrui333** [getgauge/gauge#2040]
**Describe the bug**
gauge 1.3.1 failed to install plugin on apple silicon

```
==> /opt/homebrew/Cellar/gauge/1.3.1/bin/gauge install
Compatible version of plugin  not found. Installing plugin ...
Failed to install plugin ''.
Reason: Invalid plugin name or there's a network issue while fetching plugin details.
Compatible version of plugin html-report not found. Installing plugin html-report...
Download URL for 'arm64' architecture is not set for this plugin. Falling back to 'x86_64', but this may cause issues.
........................
Failed to install plugin 'html-report' version 4.0.12.
```

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. install gauge 1.3.1
2. gauge install the `html-report` plugin
3. See error

**Additional context**
relates to Homebrew/homebrew-core#80714

**Comment by zabil** [comment]
Should work now with the new html plugin release https://github.com/getgauge/html-report/releases/tag/v4.1.0

**Comment by sriv** [comment]
We still need to update gauge-repository. It will require adding fields to the json for `arm64`

**Comment by sriv** [comment]
Actually this has nothing to do with any of the recent changes.

Gauge has this line -> https://github.com/getgauge/gauge/blob/master/plugin/install/install.go#L592 which assumes that the manifest will always have `language` key (a reasonable expectation, but better to be defensive here).

The homebrew formula tests for gauge installation with a manifest that looks like this:

```
      {
        "Plugins": [
          "html-report"
        ]
      }
```

Now the strange thing is that golang on darwin/x86_64, the map does not take an empty string as a key, whereas on darwin/arm64 does! As a result the formula passes for macOS (intel) whereas fails for macOS (silicon).

I am pushing a change with a check for `language` present in manifest.

@chenrui333 thanks for reporting, I don't think we'd have realized this otherwise.

**Comment by chenrui333** [comment]
I will give the patch a shot.
