### ISSUE TITLE
include gauge core into maven plugin

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#206]
I should be able to run tests with maven without installing gauge manually.

**Comment by mahendrakariya** [comment]
When Gauge core (which is developed in Golang) is built, an executable file is generated. This executable should be present on the machine to run a Gauge project.

Maven can be used to manage Java dependencies. But it can't install an executable file on the machine. Because of this technical constraint, Maven can't be used to install Gauge core.

On the other hand, we have made the Gauge installation process quite simple so that users can get started quickly. But if you feel that it can be made more simpler, we'd welcome your feedback.

**Comment by haroon-sheikh** [comment]
Fair enough, I was just looking for something like cucumber where you don't need to install anything. It's just a dependency from maven.
