### ISSUE TITLE
Gauge installation is blocked by anti-virus

### ISSUE THREAD

**Issue by Sebbiv** [getgauge/gauge#2064]
**Describe the bug**
Installation is blocked by windows 10 defender, you can run it anyway but after that it is blocked by our companies anti-virus.

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Download latest gauge Windows installer
2. Open installer
3. See error

**Expected behavior**
Gauge installs without alerting windows defender

**Screenshots**
![image](https://user-images.githubusercontent.com/40171310/127807796-78a9dc96-4a12-4146-8abb-973bc3f3cbd1.png)

gauge -v
```
 - OS Windows 10 Version 21H1 (OS Build 19043.1110)

**Comment by sriv** [comment]
Some context - gauge's windows binaries and installer used to be signed using a code signing certificate which has expired.

This may have an effect on the antivirus scan, but I am unable to find any documentation to substantiate this either way.

Also, quite a few antivirus companies run scans and seem to have a reputation system to score the executables, and newer binaries suffer because they get penalized for not having enough reputation.

FWIW, here is a scan for gauge 1.4.0 x86_64 installer - https://www.virustotal.com/gui/file/1fa85d68b55e61f18a3cdf9ffac519e1763f1cef3f72aaf25af2ccb1776517a5/detection. All but one flags the installer, and we may see a different result in a few days (I have seen this in the past).

**Comment by sriv** [comment]
You're welcome, although I am aware that I offer no solution to this problem :(

This has been reported before (ex: see https://github.com/getgauge/gauge/issues/1280#issuecomment-448206855) where a user reported gauge being flagged by an antivirus. The thing with virus scan is that it is a proprietary mechanism (understandably so) and hence there is no way of knowing why gauge is being flagged.

I suppose we could wait for enough users to mark gauge as "safe" for the antivirus software to take heed. In the interim, adding gauge to a "safe-list" by your IT administrator should make it easier for you.

**Comment by Sebbiv** [comment]
Seems like the issue no longer occurs.
