### ISSUE TITLE
Gauge should handle logging for runners and plugins

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#216]
Setting `--log-level` or `--verbose` flags when invoking `gauge` does not pass these flags to the runner. This is required to have consistent logging level between Gauge and the Plugins.

**Comment by nehashri** [comment]
Instead of passing log levels to runners, it would be better if Gauge itself handles the logging for all runners/plugins. This way there will be one pattern for logging in all runners. 
We can intercept the stdout and stderr of the plugins, parse and let Gauge decide how to log the information. This way, the log-level and verbose flags can be understood by Gauge only and handle the output appropriately. 

**Proposal:**
Gauge will pass a writer to all plugins (one for stdout and one for stderr). The plugins will write onto this writer instead of the standard stdout and stderr. Gauge will read the contents written on these writers and appropriately writes to stdout/stderr and log files with the correct format.

**Fatal Errors :**
 A plugin can error out after a fatal error occurs. Gauge should log the fatal error to the console and also collect all the fatal errors that have occurred and output a consolidated list of formatted errors after execution.

Pros: 
- Gauge will now have complete control over logging, one central place to manage all logs.
 - The runners need not worry about logging, Gauge will handle most of this.  
- There will be one specified format for all logs. 

Cons:
 - Gauge will have to implement multiple writers to handle the logging. To be more explicit, Gauge will have to create a custom writer for all plugins (it may have to create a writer for stdout as well as stderr). So the more the number of plugins, more writers it needs to create.

**Comment by nehashri** [comment]
The logger package should be reused to achieve this. The hardcoding done https://github.com/getgauge/gauge/pull/1402 should be fixed too.

**Comment by Debashis9012** [comment]
This enhancement has been verified and found fixed. 
Tested version: ``` 1.0.6.nightly-2019-05-31```

**Comment by nehashri** [comment]
Gauge doesn't seem to honour the log level settings given. It seems to write to the console always.

**Comment by Debashis9012** [comment]
This enhancement has been verified and found fixed. 
Tested version: `Gauge version: 1.0.7.nightly-2019-09-16`
