### ISSUE TITLE
How to set file encoding?

### ISSUE THREAD

**Issue by falkoschumann** [getgauge/gauge#218]
My Java source files are written with ISO-8859-1. Gauge expected UTF-8. So I get an error `error: unmappable character for encoding UTF-8`

How can I set the proper file encoding?

**Comment by mahendrakariya** [comment]
You can set the `JAVA_TOOL_OPTIONS` env variable to `-Dfile.encoding=UTF8`.
[This particular question](http://stackoverflow.com/questions/361975/setting-the-default-java-character-encoding) on Stack Overflow has more details.

If you are using some IDE like IntelliJ, we would recommend you to change the default file encodings to UTF8 in the IDE settings.

**Comment by falkoschumann** [comment]
I set `JAVA_TOOL_OPTIONS = -Dfile.encoding=ISO-8859-1` in the `java.properties` of my default environment. Also I see the expected message *Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=ISO-8859-1* while running gauge. But the error is still. The last error is `[CRITICAL] Failed to start gauge API: Runner exited with error: exit status 1`

**Comment by falkoschumann** [comment]
My problem with the encoding. In this project I must use ISO-8859-1 by requirement. So I can not take the easy option and change encoding to UTF-8.

**Comment by apoorvam** [comment]
Can you please check if this is working for you : 
* Create a new Gauge project.
* Set file encoding to `iso-8859-1`. If you are using IntelliJ, you can do this: File-> Encoding -> `iso-8859-1` and convert your source file to corresponding encoding format.
* Execute the spec.

This works for me with `iso-8859-1` file encoding.

**Comment by falkoschumann** [comment]
Great it works. Thanks.

But if I create the Gauge project with the Eclipse plug-in or with the command line tool, it does not work. But it's O.k. I can not change the encoding, but I can switch to IntelliJ. Closed for me.

**Comment by mahendrakariya** [comment]
@falkoschumann glad to know it worked for you.

As you said, the solution works on IntelliJ, but not on command line. We're not sure if this would be enough for you. But to get it to work across both, we will have to make some changes to the codebase.

Gauge creates (and recommends) the spec files to be utf8 encoded. If the spec files and implementation files have different encodings, there are chances of unexpected behavior. Hence, Gauge-java explicitly passes `-encoding utf8` argument to javac in [gauge-java.go](https://github.com/getgauge/gauge-java/blob/master/gauge-java.go#L321).

For your case, to make it work in command line as well, we will have to add support for other encodings as well. We have created an [issue](https://github.com/getgauge/gauge/issues/220) for this. Please note that we won't be able to pick this up right now since we are in the middle of another feature.

But if it's absolutely necessary for you to make the specs run on command line, you can change the javac argument locally and build it. Let us know if you need any help with this.

Since it's working for you on IntelliJ, I will take the liberty to close this issue. Feel free to reopen it if you run into some other problem.
