### ISSUE TITLE
NoSuchMethodError: org.reflections.util.ClasspathHelper.forJavaClassPath

### ISSUE THREAD

**Issue by jeremy-flusin** [getgauge/gauge#230]
Hi everyone,

I tried to install Gauge with:

- Ubuntu (15.04 64 bits)
- Oracle JDK (build 1.8.0_60-b27)
- Gauge (0.1.8)
- Gauge java plugin (0.2.2)

I followed the tutorial to run the hello_world spec generated by "gauge --init java" but no step can be executed. Here's the stack:
```
[INFO] Exception in thread "main" 
[INFO] java.lang.NoSuchMethodError: org.reflections.util.ClasspathHelper.forJavaClassPath()Ljava/util/Collection;
[INFO] at com.thoughtworks.gauge.scan.ClasspathScanner.createReflections(ClasspathScanner.java:57)
[INFO] at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:37)
[INFO] at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:36)
```
My team managed to install it on same configuration and it worked with no problem. Can you help me on this ?

Thanks for your work, Gauge rocks.

**Comment by apoorvam** [comment]
@jeremy-flusin, Welcome to Gauge!
It looks like something went wrong with gauge-java plugin installation. Can you please make sure that there is `reflections-0.9.10.jar` in location where Gauge plugins are installed (`~/.gauge/plugins` for linux). 

If not, you can uninstall the plugin with : `gauge --uninstall java` and try installing java plugin manually as:

* Download Gauge-java plugin [here](https://github.com/getgauge/gauge-java/releases/tag/v0.2.2).
* Install it using `gauge -f path_to_downloaded_file --install java`

Let us know if you executing with IntelliJ or command-line?

**Comment by mahendrakariya** [comment]
We investigated further on our side and found out that there is  a bug in the packaging of gauge-java plugin. Multiple versions of reflections jar are getting packaged. We have created an issue (https://github.com/getgauge/gauge-java/issues/33) and will fix it soon.

In the meanwhile, as Apoorva suggested, please ensure that only v0.9.10 of reflections jar is present in the directory `~/.gauge/plugins/java/0.2.2/libs`. That should fix the issue you are facing.

Let us know how it goes.

**Comment by mahendrakariya** [comment]
@jeremy-flusin thanks for reporting this. 

We have fixed the issue in [latest version (0.3.1)](https://github.com/getgauge/gauge-java/releases/tag/v0.3.1) of gauge-java plugin. To use this you will need to have the latest gauge version as well. 

We have released version 0.2.0 of Gauge. With Gauge 0.2.0, all the plugins will have to be updated to the latest version. Please [download and install](getgauge.io/download.html) it and run `gauge --update-all` to update all plugins.

**Comment by jeremy-flusin** [comment]
Yeah ! I had reflections-0.9.9-RC1.jar in my java plugin libs. Updating solved the problem !

Thanks for your support and your amazing work :)

**Comment by deepthigc** [comment]
So lovely to hear you like Gauge, thank you. We'd love to hear what you think about Gauge as you continue to use it.

**Comment by sreejitheday** [comment]
@deepthigc @mahendrakariya 

I am getting the same error while executing a test case from IntelliJ.  My machine has

Windows 8 64 bit
Gauge 0.2.0
Gauge java 0.3.1
JDK 1.7

Verified that "reflections-0.9.10.jar" file is present in C:\Users\user\AppData\Roaming\gauge\plugins\java\0.3.1\libs folder.

Getting the following error while executing a test case:

"C:\Program Files\Gauge\bin\gauge.exe" --simple-console "C:/Git/automation-gauge/specs/Admin Login.spec:0"
15:01:18.742 [INFO] Exception in thread "main" 
15:01:18.743 [INFO] java.lang.NoSuchMethodError: org.reflections.util.ClasspathHelper.forJavaClassPath()Ljava/util/Set;
15:01:18.743 [INFO] 	at com.thoughtworks.gauge.GaugeRuntime.scanForStepImplementations(GaugeRuntime.java:161)
15:01:18.743 [INFO] 
15:01:18.743 [INFO] 	at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:143)
15:01:18.743 [INFO] 
15:01:18.770 [INFO] process C:\Program Files\Java\jdk1.7.0_51\jre\bin\java.exe with pid 9644 quit unexpectedly. exit status 1
15:01:19.411 [ERROR] Validation failed. The following steps have errors
15:01:19.411 [ERROR] C:\Git\automation-gauge\specs\Admin Login.spec:9: WSASend tcp 127.0.0.1:51777: An existing connection was forcibly closed by the remote host.. Login to adminNet
15:01:19.411 [ERROR] C:\Git\automation-gauge\specs\Admin Login.spec:10: WSASend tcp 127.0.0.1:51777: An existing connection was forcibly closed by the remote host.. Logout from adminNet
15:01:19.427 [ERROR] Failed to initialize suite datastore. Error: WSASend tcp 127.0.0.1:51777: An existing connection was forcibly closed by the remote host.
[Html Report Plugin] : Sucessfully generated Html-report to => C:\Git\automation-gauge\reports\html-report
15:01:19.528 [INFO] Specifications: 	0 executed, 0 passed, 0 failed, 0 skipped
15:01:19.528 [INFO] Scenarios: 	-1 executed, -1 passed, 0 failed, 1 skipped
15:01:19.528 [INFO] Total time taken: 0

Can you help me to resolve this error.

Thanks,
Sreejith

**Comment by mahendrakariya** [comment]
Can you please verify that there is no other version of `reflections` jar in `C:\Users\user\AppData\Roaming\gauge\plugins\java\0.3.1\libs` or anywhere else in the classpath?

**Comment by sreejitheday** [comment]
@mahendrakariya 
project/libs folder had an older version of gauge-java- jar file. I removed that and manually copied gauge-java-0.3.2.jar to libs folder. Now I getting the below error.

"C:\Program Files\Gauge\bin\gauge.exe" --simple-console "C:/Git/automation-gauge/specs/Admin Login.spec:0"
09:55:45.429 [INFO] Exception in thread "main" 
09:55:45.430 [INFO] java.lang.NoClassDefFoundError: com/thoughtworks/gauge/SpecificationInfo
09:55:45.430 [INFO] 
09:55:45.431 [INFO] 	at java.lang.Class.getDeclaredMethods0(Native Method)
09:55:45.431 [INFO] 
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)
09:55:45.431 [INFO] 	at java.lang.Class.getDeclaredMethod(Class.java:2002)
	at org.reflections.util.Utils.getMemberFromDescriptor(Utils.java:88)
09:55:45.431 [INFO] 
	at org.reflections.util.Utils.getMethodsFromDescriptors(Utils.java:101)
09:55:45.431 [INFO] 
	at org.reflections.Reflections.getMethodsAnnotatedWith(Reflections.java:443)
09:55:45.431 [INFO] 
09:55:45.431 [INFO] 	at com.thoughtworks.gauge.scan.HooksScanner.buildHooksRegistry(HooksScanner.java:32)
09:55:45.431 [INFO] 	at com.thoughtworks.gauge.scan.HooksScanner.scan(HooksScanner.java:28)
09:55:45.431 [INFO] 
	at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:39)
09:55:45.431 [INFO] 
09:55:45.431 [INFO] 	at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:36)
09:55:45.431 [INFO] Caused by: java.lang.ClassNotFoundException: com.thoughtworks.gauge.SpecificationInfo
09:55:45.431 [INFO] 
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
09:55:45.431 [INFO] 
	at java.security.AccessController.doPrivileged(Native Method)
09:55:45.431 [INFO] 
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
09:55:45.431 [INFO] 
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
09:55:45.431 [INFO] 
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 10 more
09:55:45.455 [ERROR] Validation failed. The following steps have errors
09:55:45.455 [ERROR] C:\Git\automation-gauge\specs\Admin Login.spec:9: use of closed network connection. Login to adminNet
09:55:45.455 [ERROR] C:\Git\automation-gauge\specs\Admin Login.spec:10: use of closed network connection. Logout from adminNet
09:55:45.521 [INFO] process C:\Program Files\Java\jdk1.7.0_51\jre\bin\java.exe with pid 12484 quit unexpectedly. exit status 1
09:55:46.122 [ERROR] Failed to initialize suite datastore. Error: use of closed network connection
[Html Report Plugin] : Sucessfully generated Html-report to => C:\Git\automation-gauge\reports\html-report
09:55:46.223 [INFO] Specifications: 	0 executed, 0 passed, 0 failed, 0 skipped
09:55:46.223 [INFO] Scenarios: 	-1 executed, -1 passed, 0 failed, 1 skipped
09:55:46.223 [INFO] Total time taken: 0

Process finished with exit code 1


Can you please help to resolve this error.

Thanks,
Sreejith.

**Comment by mahendrakariya** [comment]
@sreejitheday Are you using gauge with some build tool like maven, gradle, etc?

**Comment by sreejitheday** [comment]
@mahendrakariya  No. Its a twist migrated project.

Mavenized the project now and getting the below error.

"C:\Program Files\Gauge\bin\gauge.exe" --simple-console "C:/Git/automation-gauge-mvn/specs/Admin Login.spec:0"
12:06:40.141 [INFO] Executing specification: Admin Login
12:06:40.142 [INFO] Executing scenario: Admin Login
12:06:40.695 [ERROR] Failed step: Login to adminNet
12:06:40.695 [ERROR] Error Message: java.lang.InstantiationException: ScenarioExecutionHooks
12:06:40.695 [ERROR] Stacktrace: java.lang.Class.newInstance(Class.java:359)
	com.thoughtworks.gauge.ClassInstanceManager.get(ClassInstanceManager.java:34)
	com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:30)
	com.thoughtworks.gauge.execution.HooksExecutor$TaggedHookExecutor.executeHook(HooksExecutor.java:100)
	com.thoughtworks.gauge.execution.HooksExecutor$TaggedHookExecutor.execute(HooksExecutor.java:86)
	com.thoughtworks.gauge.execution.HooksExecutor.execute(HooksExecutor.java:43)
	com.thoughtworks.gauge.processor.MethodExecutionMessageProcessor.executeHooks(MethodExecutionMessageProcessor.java:53)
	com.thoughtworks.gauge.processor.StepExecutionStartingProcessor.process(StepExecutionStartingProcessor.java:26)
	com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:72)
	com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:37)
	
12:06:41.000 [ERROR] Failed step: Login to adminNet
12:06:41.000 [ERROR] Error Message: java.lang.InstantiationException: ScenarioExecutionHooks
12:06:41.000 [ERROR] Stacktrace: java.lang.Class.newInstance(Class.java:359)
	com.thoughtworks.gauge.ClassInstanceManager.get(ClassInstanceManager.java:34)
	com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:30)
	com.thoughtworks.gauge.execution.HooksExecutor$TaggedHookExecutor.executeHook(HooksExecutor.java:100)
	com.thoughtworks.gauge.execution.HooksExecutor$TaggedHookExecutor.execute(HooksExecutor.java:86)
	com.thoughtworks.gauge.execution.HooksExecutor.execute(HooksExecutor.java:43)
	com.thoughtworks.gauge.processor.MethodExecutionMessageProcessor.executeHooks(MethodExecutionMessageProcessor.java:53)
	com.thoughtworks.gauge.processor.StepExecutionEndingProcessor.process(StepExecutionEndingProcessor.java:26)
	com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:72)
	com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:37)
	
[Html Report Plugin] : Sucessfully generated Html-report to => C:\Git\automation-gauge-mvn\reports\html-report
12:06:41.905 [INFO] Specifications: 	1 executed, 0 passed, 1 failed, 0 skipped
12:06:41.905 [INFO] Scenarios: 	1 executed, 0 passed, 1 failed, 0 skipped
12:06:41.905 [INFO] Total time taken: 866ms

Process finished with exit code 1

**Comment by apoorvam** [comment]
@sreejitheday 
Can you please check the following steps?
* Update your Gauge and all its plugins to latest versions.
You can update all Gauge plugins by:
```
gauge --update-all
```
* If you are using IntelliJ, make sure your `java` directory in Project_root/src/test/java is marked as source directory. We assume you are executing spec via IntelliJ. 
* Since its a migrated project make sure there is `twist-essentials.jar` file in your `libs` directory. This should be added during migration. If its not present, you can copy it from `TWIST_INSTALLATION_DIR/plugins/com.thoughtworks.gauge.migration.plugin/libs to MIGRATED_PROJECT/libs`. Also, `libs` should be in classpath.
* Check if you are facing this on a fresh Gauge project or only in current project.

**Comment by sreejitheday** [comment]
@apoorvam 

I created  a new Gauge project and got the below compilation error when i executed from IntelliJ. So i added gauge-java-0.3.2.jar to project/libs folder and the error resolved.

Information:Using javac 1.7.0_51 to compile java sources
Information:java: Errors occurred while compiling module 'gauge-test'
Information:10/28/2015 1:57 PM - Compilation completed with 8 errors and 0 warnings in 2s 145ms
C:\Git\gauge-test\src\test\java\StepImplementation.java
Error:(1, 30) java: package com.thoughtworks.gauge does not exist
Error:(2, 30) java: package com.thoughtworks.gauge does not exist
Error:(3, 30) java: package com.thoughtworks.gauge does not exist
Error:(17, 31) java: cannot find symbol
  symbol:   class Table
  location: class StepImplementation
Error:(8, 6) java: cannot find symbol
  symbol:   class Step
  location: class StepImplementation
Error:(16, 6) java: cannot find symbol
  symbol:   class Step
  location: class StepImplementation
Error:(25, 6) java: cannot find symbol
  symbol:   class Step
  location: class StepImplementation
Error:(20, 14) java: cannot find symbol
  symbol:   class TableRow
  location: class StepImplementation

**Comment by sreejitheday** [comment]
@apoorvam 

For the migrated project, i have done the following steps and still getting the same error.

14:07:14.579 [ERROR] Failed step: Login to adminNet
14:07:14.579 [ERROR] Error Message: java.lang.InstantiationException: ScenarioExecutionHooks
14:07:14.579 [ERROR] Stacktrace: java.lang.Class.newInstance(Class.java:359)
	com.thoughtworks.gauge.ClassInstanceManager.get(ClassInstanceManager.java:34)
	com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:30)
	com.thoughtworks.gauge.execution.HooksExecutor$TaggedHookExecutor.executeHook(HooksExecutor.java:100)
	com.thoughtworks.gauge.execution.HooksExecutor$TaggedHookExecutor.execute(HooksExecutor.java:86)
	com.thoughtworks.gauge.execution.HooksExecutor.execute(HooksExecutor.java:43)
	com.thoughtworks.gauge.processor.MethodExecutionMessageProcessor.executeHooks(MethodExecutionMessageProcessor.java:53)
	com.thoughtworks.gauge.processor.StepExecutionStartingProcessor.process(StepExecutionStartingProcessor.java:26)
	com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:72)
	com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:37)

1. Already updated the gauge to latest veresion (Gauge version 0.2.0, html-report 1.1.0, gauge-java 0.3.2)
2. twist-essentials-1.0.5.jar exist in project/lib folder
3. src/test/java set as source folder
4. commons-io-2.4.jar and org.eclipse.jst.ws.annotations.core_1.1.0.v201104031139.jar are added to project/lib folder from com.thoughtworks.twist.gauge.migration.plugin_1.0.1.13773-f33f90a3b075e3 folder

**Comment by sreejitheday** [comment]
@apoorvam

I created a new Gauge project and got the below compilation error when i executed from IntelliJ. So i added gauge-java-0.3.2.jar to project/libs folder and the error resolved.

Information:Using javac 1.7.0_51 to compile java sources
Information:java: Errors occurred while compiling module 'gauge-test'
Information:10/28/2015 1:57 PM - Compilation completed with 8 errors and 0 warnings in 2s 145ms
C:\Git\gauge-test\src\test\java\StepImplementation.java
Error:(1, 30) java: package com.thoughtworks.gauge does not exist
Error:(2, 30) java: package com.thoughtworks.gauge does not exist
Error:(3, 30) java: package com.thoughtworks.gauge does not exist
Error:(17, 31) java: cannot find symbol
symbol: class Table
location: class StepImplementation
Error:(8, 6) java: cannot find symbol
symbol: class Step
location: class StepImplementation
Error:(16, 6) java: cannot find symbol
symbol: class Step
location: class StepImplementation
Error:(25, 6) java: cannot find symbol
symbol: class Step
location: class StepImplementation
Error:(20, 14) java: cannot find symbol
symbol: class TableRow
location: class StepImplementation

**Comment by apoorvam** [comment]
@sreejitheday 
Can you please remove the `gauge-java-0.3.2.jar` in libs directory and add it as follows:
* In IntelliJ IDE, go to Project Settings -> Modules -> Dependencies.
* Select to add(+) jars/directories and point it to Gauge-java install location/libs.
In windows it will be `%APPDATA%\gauge\plugins\java\0.3.2\libs`.
This should set the Gauge Java plugin as dependency, instead of adding it to libs directory.

**Comment by sreejitheday** [comment]
@apoorvam 

I am getting compilation error after removing gauge-java-0.3.2.jar from lib and added "C:\Users\user\AppData\Roaming\gauge\plugins\java\0.3.2\libs" to dependency.

C:\Git\automation-gauge\src\test\java\StepImplementation.java
Error:(1, 30) java: package com.thoughtworks.gauge does not exist
Error:(2, 30) java: package com.thoughtworks.gauge does not exist
Error:(16, 31) java: cannot find symbol
  symbol:   class Table
  location: class StepImplementation

**Comment by apoorvam** [comment]
If the project build is failing with compilation error but the Java Files are not mark any errors, please follow as mentioned in [trouble shooting](http://getgauge.io/documentation/user/current/troubleshooting/intellij.html#3-project-build-failing-with-compilation-error-but-the-java-files-do-not-mark-any-errors).
Please check if you are able to successfully execute from command line. In your project directory, you can do `gauge specs` to execute.

**Comment by sreejitheday** [comment]
@apoorvam 

Updated IDEA_INSTALLATION\bin\idea.exe.vmoptions file but still got the same compilation error.

Got the below error when i exeucted from command line using the command gauge --tags "sreejith" specs

c:\Git\automation-gauge>gauge --tags "sreejith" specs
17:27:39.421 [INFO] Note: Some input files use or override a deprecated API.
17:27:39.422 [INFO] Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
17:27:44.341 [INFO] Exception in thread "main"
17:27:44.342 [INFO] java.lang.NoClassDefFoundError: com/thoughtworks/gauge/SpecificationInfo
17:27:44.342 [INFO]
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)
        at java.lang.Class.getDeclaredMethod(Class.java:2002)
        at org.reflections.util.Utils.getMemberFromDescriptor(Utils.java:88)
        at org.reflections.util.Utils.getMethodsFromDescriptors(Utils.java:101)
        at org.reflections.Reflections.getMethodsAnnotatedWith(Reflections.java:443)
        at com.thoughtworks.gauge.scan.HooksScanner.buildHooksRegistry(HooksScanner.java:32)
17:27:44.342 [INFO]
        at com.thoughtworks.gauge.scan.HooksScanner.scan(HooksScanner.java:28)
        at com.thoughtworks.gauge.scan.ClasspathScanner.scan(ClasspathScanner.java:39)
        at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:36)
Caused by: java.lang.ClassNotFoundException: com.thoughtworks.gauge.SpecificationInfo
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
17:27:44.342 [INFO]     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 10 more
17:27:44.350 [ERROR] Validation failed. The following steps have errors
17:27:44.350 [ERROR] c:\Git\automation-gauge\specs\Admin Login.spec:9: use of closed network connection. Login to adminN
et
17:27:44.350 [ERROR] c:\Git\automation-gauge\specs\Admin Login.spec:10: use of closed network connection. Logout from ad
minNet
17:27:44.365 [ERROR] Failed to initialize suite datastore. Error: use of closed network connection
[Html Report Plugin] : Sucessfully generated Html-report to => c:\Git\automation-gauge\reports\html-report
17:27:44.388 [INFO] process C:\Program Files\Java\jdk1.7.0_51\jre\bin\java.exe with pid 4752 quit unexpectedly. exit sta
tus 1
17:27:44.466 [INFO] Specifications:     0 executed, 0 passed, 0 failed, 0 skipped
17:27:44.466 [INFO] Scenarios:  -1 executed, -1 passed, 0 failed, 1 skipped
17:27:44.466 [INFO] Total time taken: 1ms

c:\Git\automation-gauge>

**Comment by apoorvam** [comment]
Can you please check the version of `twist-essentials.jar` in your libs? The latest version of it is 1.0.9.

**Comment by sreejitheday** [comment]
@apoorvam 

I have twist-essentials-1.0.5.jar. where can i download twist-essentials-1.0.9?

**Comment by apoorvam** [comment]
@sreejitheday We have sent you an email with the jar file attached. Please let us know if you got it in your inbox (as part of your ticket 25936). 
If you have latest version of Twist i.e.15.2.9, you can get it from `TWIST_INSTALLATION_DIR/plugins/com.thoughtworks.gauge.migration.plugin/libs`.

**Comment by sreejitheday** [comment]
@apoorvam 

After adding the latest twist-essntials jar, it start working from command line but same compilation error from IntelliJ.

Can you send me the installer for Twist 15.2.9. The one i have is Twist version - 15.2.0.13766.

**Comment by deepthigc** [comment]
Hi Sreejith,

We will be happy to mail you the installers you need. Since this forum is a
Gauge forum, we prefer not to share any Twist related information here,
it's not very useful for all the other Gauge customers. I know we asked you
to move your Gauge queries to google groups and that is definitely the way
we'd want it. It's only for the Twist stuff that I am asking we communicate
outside of this forum.

We have a support ticket from you and we will follow up on that ticket with
the installer information you need. I hope this makes sense.

Thanks for understanding.

-Deepthi

**Comment by sreejitheday** [comment]
Thank you Deepthi. Still I am getting error while running gauge test from IntelliJ.

Thanks,
Sreejith.

**Comment by sreejitheday** [comment]
@apoorvam 

I am able to run the test case from IntelliJ also after updating the twist-essntials jar. Thanks a lot for your help.

**Comment by deepthigc** [comment]
Wonderful! Great to hear that Sreejith.

**Comment by sivnz** [comment]
@apoorvam Hey apoorvam! How's going? I would like to receive an copy of the email with the twist jar file, please.
Im a new gauge user and im having the same issues that this man had.
Thanks in advance!

**Comment by apoorvam** [comment]
Hey @sivnz, Welcome to Gauge!
Are you facing this issue with a project migrated from Twist to Gauge? If so, you can raise a request [here](https://support.thoughtworks.com/anonymous_requests/new) and we can help you. It would be great if you send us the error messages/stack trace as well.

If it's a fresh Gauge project, you would not need this jar. You can create a new issue on GitHub if you have any questions.
