### ISSUE TITLE
Gauge 0.2.1 not available on chocolatey

### ISSUE THREAD

**Issue by ketan** [getgauge/gauge#237]
I'm trying to install 0.2.1 on windows, and found that a version is not available for windows. Does your release process not upload to chocolatey?

**Comment by deepthigc** [comment]
Hi Ketan,

We have sent in a request(for Gauge 0.2.1) to upload to chocolatey, but
they have not been able to process our request because they seem to have
about 2-3 weeks of work pending. As a result they are not accepting any
more requests for a little while.

We're working with them to get this sorted. But it may take a while and
they haven't been able to tell us how long yet.

For now, you will have to download use the installer. Sorry about this.

**Comment by Thunderforge** [comment]
To add to what @deepthigc said, there is a message about this at https://chocolatey.org/notice

> Currently we have a very large backlog of packages in moderation queue (popularity is a double-edged sword) and are actively addressing the situation, but as a result moderation may take upwards of two or more weeks until we resolve issues. 

> For urgent issues (including packages that are security releases), please reach out to us immediately on Gitter.

New releases of Gauge go through that same moderation queue, so unless there are urgent issues such as security holes, the Chocolately team says that it will take two or more weeks for them to post it.

**Comment by haroon-sheikh** [comment]
@ketan @Thunderforge 0.2.1 is now on chocolatey.

**Comment by sriv** [comment]
Sorry, this wasn't updated, thanks @haroon-sheikh for following this up.
