### ISSUE TITLE
Step passed messages no longer in console output

### ISSUE THREAD

**Issue by ocary** [getgauge/gauge#239]
Upgraded from v0.1.7 to 0.2.1 and the "Step Passed" console messages are no longer showing during spec execution.   Having step status messages on by default, rather than having to turn on the the verbose tag would be better.

Example from 0.1.7:   Step Passed => * Verify score is "4"

**Comment by deepthigc** [comment]
Hi,

We have received a few questions about this particular issue. There are a
few issues that need fixing in the console output area.

1. Colour schemes - we are looking into another library
2. Amount of information shown by default - this is especially hard because
a lot of people we speak to want varying amounts of information. We have
tried to handle this by providing flags so each user can get the kind of
output they prefer. A lot of users asked for even lesser information on the
console. I hope this makes sense.

For now,using the flag will give you the information you need. We're
working on this issue, we will have something soon.

**Comment by Thunderforge** [comment]
My team has the same complaint. We have no way of knowing where in the execution we are. Are we on the second to last? Did it freeze on the first? How do we know? Many of our specs run for several minutes, so we want to know how far we've gotten.

I should also add that our primary use case is working with specs in Intellij IDEA. Right now, all execution is shown in the Run output, which is identical to the command line. If the Intellij plugin were made to be more like JUnit in that it graphically lists execution and their status, then we wouldn't care what the default output and the command line is.

To us, it seems obvious that knowing where in the spec we are should be shown be default. I'm curious why some have wanted even less default information though. Do they think it clogs up their log files? If so, that might be a different use case where they don't care where they are in a spec (perhaps they are doing an automated run in a continuous integration tool?).

Regarding color schemes, I personally don't care about them and see nothing wrong with the current output. It just seems kind of inappropriate for a console that is always white text on black. I would like colors in Intellij though, again, like JUnit.

**Comment by mahendrakariya** [comment]
We will definitely move to JUnit like execution results in IDEs. But it will take us some time to release it since it requires design change.

**Comment by kaustavdm** [comment]
This is being taken care of as part of fixing #212. It will take some time before this is released because it needs a good amount of internal changes. We're on it :smile:

**Comment by mahendrakariya** [comment]
@ocary We have released Gauge v0.3.0 with support for colored console reporting. To see step details, please run with `--verbose` flag.
