### ISSUE TITLE
Duplicate log level when running code that calls logging library (e.g. log4j, SLF4J)

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/gauge#245]
It is common in our Java code to use SLF4J as a Java logging library. For instance, we may have code that looks like this:

    @Step("Do something")
    public void doSomething() {
        logger.info("Something cool is about to happen!")
        //more code
     }

However, the Gauge log for this looks a bit awkward with the logging level `INFO` appearing twice.

    [runner:2] [INFO] 5939565 [main] INFO  com.example.SomethingClass  - Something cool is about to happen!

What I would expect is for the two logging level statements to be merged into one:

    [runner:2] [INFO] com.example.SomethingClass  - Something cool is about to happen!

I suspect that the first logging level may be Gauge-specific and the second one may be our code-specific. In that case, I suppose the code-specific one should take priority.

**Comment by sriv** [comment]
Your suspicion is correct, Gauge uses a logger itself, and this behaviour is because the Test code's logger sends out a formatted string to the console output, which is intercepted by gauge and passed to Gauge's logger, which prints this as an `INFO`. 

I further suspect that if you were to use a different logging level, i.e. `WARN` in your test code, this would get translated to something like this:

```
[runner:2] [INFO] 5939565 [main] WARN  com.example.SomethingClass  - Something cool is about to happen!
```

which is quite counter-intuitive. [note: I haven't actually tried this out, but this is my strong suspicion]

**Comment by Thunderforge** [comment]
You are correct about the mixed logging levels. I just tried that and got the following:

    13:09:07.556 [INFO] 48382 [main] WARN  com.example.SomethingClass  - Something cool is about to happen!

**Comment by mahendrakariya** [comment]
@Thunderforge Is this still an issue?

**Comment by Thunderforge** [comment]
I believe that it is fixed now. Thanks!

**Comment by mahendrakariya** [comment]
Thanks for the update!
