### ISSUE TITLE
After hooks not run when scenario fails due to an uncaught exception

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#248]

**Comment by apoorvam** [comment]
@haroon-sheikh 
We did make sure now that after hooks are executing if a scenario fails due to an uncaught exception. Here is a [gist](https://gist.github.com/apoorvam/0b8b42103da8e78753df) for reference.

Can you please check if you are using latest versions of Gauge and its plugins: 
* Gauge - 0.2.1
* Gauge-Java - 0.3.3

**Comment by mahendrakariya** [comment]
@haroon-sheikh Do you have any update on this?

**Comment by haroon-sheikh** [comment]
Unable to reproduce the issue. Will key an eye on it. Closing for now.

**Comment by mahendrakariya** [comment]
Thanks!
