### ISSUE TITLE
unable to upgrade gauge on mac

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#250]
Unable to upgrade to latest version of gauge using `brew` or the `pkg installer`

the errors are below:

on `brew install gauge`

```bash
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink share/gauge/gauge.properties
/usr/local/share/gauge is not writable.
```

on `brew link gauge`

```bash
Linking /usr/local/Cellar/gauge/0.2.1... 
Error: Could not symlink share/gauge/gauge.properties
/usr/local/share/gauge is not writable.
```

**Comment by haroon-sheikh** [comment]
Since the gauge is rapidly growing and versions are continuously changing, there should be a way of upgrading gauge from command line on both windows and macs.

**Comment by haroon-sheikh** [comment]
I managed to fix the issue by running `sudo chown -R `whoami`:admin /usr/local/share/`

However I was then getting an error installing/updating the plugins with the following error:

```bash
[ERROR] java : Invalid plugin : Could not download java-install.json file. exit status 35
```

**Comment by mahendrakariya** [comment]
@haroon-sheikh Sorry to hear about the troubles.

On Mac, we would recommend using **one of either** brew or the pkg installer. This error is likely to occur if user has installed Gauge with pkg installer and trying to update using brew or vice versa. 

Exit status 35 is due to SSL connection error. Could you please try again?

You can also use `gauge --update-all` to update all the installed plugins at once.

If you wish to update via command line, on Mac, we recommend you **always** use `brew` and on Windows, we recommend you to use [chocolatey](http://getgauge.io/documentation/user/current/getting_started/download_and_install.html#using-chocolatey). 

We have an [open issue](https://github.com/getgauge/gauge/issues/197) for checking product updates. As a part of this, we will be showing a message to the user to upgrade Gauge and / or plugins.

**Comment by haroon-sheikh** [comment]
@mahendrakariya I installed gauge with brew this.

I'm still getting exit status 35 for all of the plugins.

**Comment by mahendrakariya** [comment]
Could you please tell us whether Gauge is using wget or curl to download the plugins?

**Comment by haroon-sheikh** [comment]
@mahendrakariya its using `curl`

**Comment by haroon-sheikh** [comment]
I installed `wget` and tried `gauge --update-all` and this time it's managed to update everything as expected.

Is it not supposed to work with `curl`?

**Comment by mahendrakariya** [comment]
It should work with `curl` as well. But, you are getting exit status 35. This error generally means that there was a SSl/TLS handshake failure when `curl` was trying to connect to github. 

Can you provide us the complete error message?

**Comment by mahendrakariya** [comment]
@haroon-sheikh Do you have any update on this?

**Comment by haroon-sheikh** [comment]
This works well with wget. Will create a separate issue for curl.

**Comment by mahendrakariya** [comment]
Thanks for the update!
