### ISSUE TITLE
Execute all verifications irrespective of the result of the previous verification

### ISSUE THREAD

**Issue by deepthigc** [getgauge/gauge#255]
When executing a scenario, if a step that is performing verifications fails, Gauge stops execution and reports an error. 

Expected Behaviour:

It should have soft assert type of behaviour. If a  step that is verifying something fails, then Gauge SHOULD proceed to the next step. However, if the step that fails is not verifying anything, then the current behaviour should be retained. 

One way to do this would be to identify a verification step by checking if an assertion exception is thrown and implement custom logic in this case. 

This should work for 

- [x] Java
- [x] C#
- [x] Ruby

**Comment by Thunderforge** [comment]
I'm not sure I'm understanding why this new behavior would be beneficial, and I can imagine some situations in which it could be harmful.

I expect that Gauge should behave the same way that JUnit does: if you have three assertions in a row and the first one fails, execution stops. This seems to be the most logical way for most Gauge specs too. For example, we might have the following spec:

    * Click on button "Display Dialog"
    * Verify that dialog is displayed
    * Click on button "OK" in dialog

In this case, I would want for scenario execution to fail on the verification step. I do *not* want for execution to continue because clicking on the "OK" button is certainly going to fail.

In some cases, this proposed behavior can also be destructive.

    * Load data into form fields from CSV
    * Verify that form fields match expected values
    * Click "Send to Database" button

In this case, the end result is that unexpected data is fed into the database.

Is there something I'm missing? With my current understanding, I would be strongly against changing this behavior.

**Comment by deepthigc** [comment]
@Thunderforge You're right. We did consider this use case. I agree it could be harmful. However, we did have a request that if a scenario only fails at a verification, then it makes sense for the steps to proceed to the next verification irrespective of the failure, similar to a soft assert. But like you pointed out, this will cause trouble in the scenario above.

We did not intend to make this the default behaviour. Our plan was to add in a configuration for this, so it can be toggled on or off, as the user might need. I suppose what might be needed is a way to turn these on selectively, and that is probably a bad idea and an anti-pattern.

We raised this issue as this came up in some conversations.

**Comment by Thunderforge** [comment]
If someone really wants this "soft assert" behavior, couldn't they use TestNG's [`SoftAssert`](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/asserts/SoftAssert.java) class within their Gauge step? I think that Gauge should respect the behavior of `SoftAssert`, but not change the behavior of `Assert` from either TestNG or JUnit.

**Comment by ericblackburn** [comment]
Soft Asserts, aka Verify() in Twist, are a fundamental asset for complex system tests.  Gauge not supporting the option for some soft asserts is currently preventing my team from being able to migrate from Twist to Gauge.  

First, I agree that JUnit's Assert should not be treated as a soft assert.  That isn't its intent.  

Twist understood this.  Twist had a Verify(), soft assert, that would fail the step and continue execution, when the passed in condition was "false".  Importantly, the step would show as red in the HTML Report.  Making the failed steps in a scenario easy to track down.

Seemingly, Verify() can be added to Gauge in a similar way to Twist.  Gauge monitors the fail/pass state of a step.  Verify() should be able to update this state without exiting the scenario.  This state could then be passed to the results.js, that the HTML Report uses, and then display the step as red in the report when a soft assert failure occurs.  Alternatively, provide an @AfterStep execution hook that allows a developer to update pass/fail state of a step explicitly.  That way we can write our own Verify() methods.

Here are some example uses cases, simplified but should help understand the importance of a soft assert:

Validating multiple items on a GUI page, if Gauge stops on validating image 1, then the test doesn't inform the test team whether the rest of the expected state was met. Re-writing this scenario to have to login each time I want to validate some state abou this tab would be prohibitively expensive from a time perspective.  I am not testing how often I can login, I am testing that when I land on the Tab, the user sees a default state that includes multiple items.  The items are not dependent on each other and therefore shouldn't prevent the validation of another item just because 1 of the items isn't in a desired state.
1. Navigate to URL
2. Login
3. Navigate to Tab
4. Validate that image 1 shows
5. Validate that image 2 shows
6. Validate form is visible.
7. etc

A non-gui example, I shouldn't have to re-write the test for a stored procedure each time I want to verify something different about the DB, after having run the stored procedure.  The test step that failed should be obvious to the person looking at the HTML Report.  Furhermore, what if running the stored procedure takes a couple of minutes.  These are System tests, not Unit tests.  Re-running the stored procedure is resource intensive in this case and the validation steps provide a lot of insight into the after state of running the stored procedure.  If Table 1 doens't reach the desired state, that doesn't Have to mean that Table 2 isn't a valuable validation point.
1. Run database store procedure that is meant to update several parts of the DB
2. Validate table 1 was updated correctly
3. Validate table 2 was updated correctly
4. etc.

These are simple examples.  Yes, making multiple verification could be rolled into one step.  From my experience, this is an anti pattern for a DSL structured test that uses an Object Oriented test harness.  I am writing my steps to be re-usable.  I shouldn't have to write a new step each time I want to test something about my product. I should re-use a step and pass in a parameter to allow the step to perform a new verification, such a  "image1.png" or "image2.png". Furthermore, I should be able to easily parse my test results via the HTML Report and know exactly what test expectation failed.  

Twist was powerful for functionally testing systems, especially web applications, due to having both Asserts and Verifies (soft asserts).  Gauge needs to carry on this tradition by respecting what Twist excelled at.

**Comment by mahendrakariya** [comment]
> Alternatively, provide an @AfterStep execution hook that allows a developer to update pass/fail state of a step explicitly.

I am digressing a bit from the actual discussion. This comment is not intended to make a case for or against this feature. 

But I would just like to point out that Gauge does have `@BeforeStep` and `@AfterStep` hooks. The documentation has more details. http://getgauge.io/documentation/user/current/test_code/java/execution_hooks.html

**Comment by ericblackburn** [comment]
It does, but the hook doesn't provide an ExecutionContext feature for the step that allows for the Pass/Fail state to be changed.

**Comment by Thunderforge** [comment]
What would be the benefit of creating a new Verify() method like Twist had over TestNG's [`SoftAssert`](https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/asserts/SoftAssert.java)? If SoftAssert were integrated better into Gauge, would that solve your problem?

> It does, but the hook doesn't provide an ExecutionContext feature for the step that allows for the Pass/Fail state to be changed.

Not sure about changing the pass state, but you can just call JUnit's `Assert.fail()` in the @AfterStep method. I could see calling SoftAssert's `assertAll()` during this method, and having the reporting tie into this.

**Comment by ericblackburn** [comment]
TestNG soft assert, or AssertJ, could be used effectively with Gauge's execution hooks.  The missing piece is the failure's visibility in the HTML Report, or any report that Gauge will have in the future.  With soft asserts, the scenario is showing as failed in the HTML Report, but the step itself is showing as having passed (has a green marker for the step instead of red).  

If execution reports, such as the HTML Report, handled the presentation of the soft assert clearly (see Twist as an example), my triage team (and those with less experience) would be able to diagnose the problem much faster.  

A clear report is vital when non-dev types are trying to understand why a system's acceptance tests failed.  The Green/Red indicators next to the steps are super simple for a non-dev type to understand.

**Comment by kbangur** [comment]
I agree with ericblackburn. Especially for any of the soft assertion(TestNG soft assert, or AssertJ) failure NOT showing up in gauge reports - because gauge is not tracking soft assertion failures and so there is no red indicator on soft assertion failures.

In my case, we have certain "navigation" tests that look for multiple links in certain page. It would be okay to have some link and not have others. But I cant fail when I do not find certain link - but would rather want to continue my test to see for other links that are available. I have reusable methods to soft assert links availability.

**Comment by bharat2014** [comment]
I agree with @ericblackburn  and @kbangur, we are using our own version of soft asserts and using Gauge.writeMessage to write soft assert failure info to the reports at step level. But we don't have screenshots for soft failures. It would be nice if we have a way to mark a soft failed step as failed and get the screenshot in the report.

**Comment by tk8817** [comment]
Adding my hat into the ring, this is the killer feature we are looking for to finally cut the cord with Cucumber. Validate vs assert is an amazing feature which cuts down on 'wasted' steps. In cucumber, if you want to ensure all of your verifications are run, you have to re-run the full scenario which could be minutes of setup (navigate, register, login, etc...). When teams parallelize their runs, having validate (or soft-assert) can help drastically reduce runtimes.

**Comment by kaustavdm** [comment]
@BugDiver did a spike on this with the Java runner and here are the quick findings:

1. Nothing changes in the markdown layer
2. Nothing changes in the `proto` layer. There is already an option present in `proto` that lets a runner mark a step as recoverable. We don't use it now. Gauge core can use this option to figure out whether to continue executing the rest of the steps in the scenario or break. This means, better backward compatibility.
3. Introduce a new annotation in the Java runner called **`@ContinueOnFailure`**. This annotation has to be explicitly marked on a step implementation that is not supposed to break on failure.
4. Console reporting needs to change to provide a better UX for non-verbose runs. Otherwise, console shows stacktraces of errors in between printing the status for next steps. This is bearable for verbose runs, but gets difficult to understand for non-verbose runs.

## Show and tell

Consider this example:

```markdown
# Test all verifications

## Test break on failure

* I break
* Hello

## Test continue on failure

* I don't break
* Hello
```

```java
@Step("Hello")
public function hello() {
    // Non-failing code goes here
}

@Step("I break")
public function ibreak() {
    assertFalse(true);
}

@Step("I don't break")
@ContinueOnFailure
public function nobreak() {
    assertFalse(true);
}
```

With this proposal, the second scenario (`Test continue on failure`) will execute the step `Hello` even though the first step in that scenario will throw an `AssertionError`. This is because the implementation of first step (the method `nobreak()`) is annotated with `@ContinueOnFailure`. The first scenario (`Test break on failure`) breaks at the first step because its implementation throws an `AssertionError` and is not annotated with `@ContinueOnFailure`.

## Caveat

Gauge will still, by default, make all step implementations break on failure, unless marked with **`@ContinueOnFailure`** (for Java). This means there is no way to globally mark a test run to treat all steps to continue on failure.

If there is a need to have such a global flag, either through a environment property or through an argument to `gauge`, we are all ears.

**Comment by Thunderforge** [comment]
I really like this proposal and the annotation approach. An alternative would be adding an extra, optional parameters to step annotation (e.g. `@Step(name = "I don't break", breakOnFailure = false)`), but I think that I prefer a separate annotation for simplicity.

Would this be continuing on any failure or just an `AssertionError`? Personally, I wouldn't want it to continue if I ran into something like a `NullPointerException`, even if it were annotated with `@ContinueOnFailure`.

**Comment by kbangur** [comment]
Thoughts from my side - especially looking at backward compatibility with soft assertion as I am moving from Twist to Gauge and had used soft assertions heavily earlier:

1. Considering a Step implementation method having multiple assert statements but only one (let's say) soft assertion statement, how would we make @ContinueOnFailure to continue only for a soft  assertion failure but still fail otherwise?

2. Let's say I have a step implementation method A (Annotated as @Step) which internally calls method B. And my soft assertion logic is in the non-step method B. Will I still be able to mark method A as @ContinueOnFailure and get the expected behaviour?

**Comment by tk8817** [comment]
@kaustavdm - very well thought out solution to the problem, thanks for all the hard work!

**Comment by apoorvam** [comment]
@Thunderforge  @kbangur  @tk8817 Thanks for all your feedback!

Just to add, this feature is to continue execution of steps further even if a step fails. Step failure can be due to any kind of failure in the step implementation, not just `AssertError`. 

@Thunderforge Yes, having a different annotation is for simplicity. There can be an enhancement to this feature to continue only on assert errors(not on something like NullPointerException in case of Java). Depending on language paradigm, we will have to decide how this can be implemented.

@kbangur Here are responses to your questions inline.

> Considering a Step implementation method having multiple assert statements but only one (let's say) soft assertion statement, how would we make @ContinueOnFailure to continue only for a soft assertion failure but still fail otherwise?

No. Gauge will not be able to differentiate if the error is a soft assert error or a normal assertion failure or in fact any other failure as Gauge is framework/driver agnostic. If a step impl method is tagged with `@ContinueOnFailure`, it will continue executing next step even if current step fails(throws any error). This is more of like soft assertion at Steps level and not at level of assertions in a method.

> Let's say I have a step implementation method A (Annotated as @Step) which internally calls method B. And my soft assertion logic is in the non-step method B. Will I still be able to mark method A as @ContinueOnFailure and get the expected behaviour?

Yes. In the below code snippet, both `my step1` and `my step2` fails. Even if `my step1` fails, `my step2` is executed because the implementation for `my step1` is marked with `@ContinueOnFailure`. However, `my step3` will not be executed as `my step2` is not marked to continue.

`mySpec.spec`
```markdown
# Spec heading

## Scenario heading
* my step1
* my step2
* my step3
```

`StepImpl.java`
```java
public void foo() {
    assertEquals("foo", "bar")
}

@ContinueOnFailure
@Step("my step1")
public void stepImpl() {
    foo()
}

@Step("my step2")
public void stepImpl2() {
    foo()
}

@Step("my step3")
public void stepImpl3() {
}

```

Let us know if you have any suggestions. :)

**Comment by kbangur** [comment]
Thanks for the response @apoorvam - The only concern that I see is with the granularity of soft assertion. With the current approach we would have Step level granularity - but this takes away the benefit of even finer control that would have been possible with individual line of code making soft assertions.

**Comment by sriv** [comment]
> Would this be continuing on any failure or just an AssertionError? Personally, I wouldn't want it to continue if I ran into something like a NullPointerException, even if it were annotated with @ContinueOnFailure.

@Thunderforge - What do you think of this:

- `ContinueOnFailure` annotation could take parameters, gathering error classes that it can safely skip. This would be an optional parameter, and user would still be able to do a parameterless `ContinueOnFailure`, which would simply ignore all errors.

- In Java, we have the language provided `java.lang.assertionerror` class, that we may be able to use in this case. However, in languages such as C#, the assertion exceptions thrown are unique to every framework AFAIK.

**Comment by Thunderforge** [comment]
> `ContinueOnFailure` annotation could take parameters, gathering error classes that it can safely skip. This would be an optional parameter, and user would still be able to do a parameterless `ContinueOnFailure`, which would simply ignore all errors.

@sriv This would probably work, but I think that I would want a way to globally set it so that only (in Java) `java.lang.AssertionError` is allowed by default. Perhaps in Gauge's `default.properties`, we could add another parameter. The default would be to allow them all:

    #Continue when any type of error is encountered
    continue_on_failure_exception_whitelist = *

And it can be configured to only allow certain errors:

    #Continue only when an AssertionError is encountered
    continue_on_failure_exception_whitelist = java.lang.AssertionError

Alternatively, Java or other languages that have equivalents to `AssertionError` could make that the default.

**Comment by sguptatw** [comment]
- Xml report does not have the relevant details
- Not yet available in ruby
-----------------
List of test cases tested so far

Report Generation
- Html report generated has the relevant details
- Xml report does not have the relevant details

Test cases
- Continue on failure in setup
- Continue on failure in teardown
- Continue on failure inside a concept
- Continue on failure in setup and having all other steps passing the scenario should fail
- Continue on failure in footer and having all other steps passing the scenario should fail
- Multiple continue on failure steps are executed till it finds a failing step or till it finds that the scenario is complete.
- All steps passing, steps with no-continue on failure continue to work as expected.
