### ISSUE TITLE
Export specs to HTML

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/gauge#290]
Users should be able to export the specs to HTML.
For more details, refer https://groups.google.com/forum/#!topic/getgauge/eDb-GAVXYjg

**Comment by bensullivan** [comment]
It would be good if this feature allowed specs to be searched, toggling of test execution time and result (so that you can just focus on the behaviour if you want to) and the grouping of specs, similar to Topics in relishapp.

Many thanks

**Comment by sriv** [comment]
[Tech Notes]

Options evaluated:

- Golang markdown libraries such as [blackfriday](https://github.com/russross/blackfriday) may not suit this requirement, since blackfriday omits tags it does not understand, as a result, comments and `tags` are left out. One option is to fork and maintain a version that is more liberal and suit's gauge's requirement.
Pros: can have a native binary making deployment/setup simple.
Cons: Loss of relevant comments/tags

- look at [jekyll](http://jekyllrb.com), and have a script/plugin that will generate a site based on the theme selected. Jekyll structure is different from gauge's convention, and requires YAML Front Matter for meta information (although optional).
Pros: Very popular, plenty of themes available.
Cons: Requires conversion from gauge to jekyll structure. Ruby needs to be installed on users machine.

- Use [mkdocs](http://www.mkdocs.org/)
Pros: Simplest to use to generate documentation. `readthedocs` theme is beautiful.
Cons: Requires conversion from `spec`, `cpt` to `md` file extension (mkdocs works only with known markdown extensions). Python and pip needs to be installed on users machine to install mkdocs.

Of these, I prefer using mkdocs.

**Comment by kashishm** [comment]
We have released a [plugin](https://github.com/getgauge/M2H/releases/tag/v0.0.1) which provides a basic `Export to HTML` functionality with filtering by tag expression. Refer [readme](https://github.com/getgauge/M2H/blob/master/README.md) for documentation. Please log an issue [here](https://github.com/getgauge/M2H/issues) if you have any feedback.
