### ISSUE TITLE
Console output does not show name

### ISSUE THREAD

**Issue by itsmemittal** [getgauge/gauge#327]
when run gauge specification, it does not show currently executing step name and display some weird P symbol for each statement.

![gauge console](https://cloud.githubusercontent.com/assets/3033471/14531373/b420d082-027a-11e6-9bb8-280b53e36dd3.png)

**Comment by mahendrakariya** [comment]
@itsmemittal This is by design.

By default, Gauge only shows the specification name and the scenario name. For each step it executes, it shows a `P` or `F` depending on whether the step passed or failed.

However, if you would you also like to see the step that is being executed, you can run Gauge with `--verbose` flag. For example, `gauge --verbose specs`. If verbose flag is passed, Gauge will show detailed output on the console.

**Comment by kashishm** [comment]
@itsmemittal Did this get resolved after adding `--verbose` flag?

**Comment by itsmemittal** [comment]
yes

**Comment by mahendrakariya** [comment]
Coool!
