### ISSUE TITLE
On a maven project, using the non-maven usage of gauge should exit gracefully

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#451]
**Expected behavior**
After giving the compilation errors gauge should exit gracefully.

**Actual behavior**
It is giving compilation errors. However it exits after a timeout.

**Steps to replicate**
1. clone https://github.com/getgauge/gauge-test-apps.git
2. cd projects/web-apps-e2e
3. mvn clean compile
4. gauge specs

**Version**

```
Gauge version: 0.4.1.nightly-2016-06-08

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-05-30)
```

**Comment by sriv** [comment]
The usage seems incorrect. In a maven project, one needs to use `mvn gauge:execute` and not `gauge specs`.

If I follow the steps and do `mvn gauge:execute` instead of `gauge specs`, I get a lot of `[ValidationError]`s, which I guess is expected.

@sguptatw - do you still think the behaviour is incorrect, if you use `mvn gauge:execute` ?
