### ISSUE TITLE
TagAggregation should have a Not operator

### ISSUE THREAD

**Issue by unibeck** [getgauge/gauge#468]
It would be nice to run hooks based on the lack of tags. I have a lot of specs that can benefit from my hook, and only have a couple specs that don't need the hook running @AfterScenario. It would look something like this @AfterScenario(tags="don'tRemoveGarbage", tagAggregation = Operator.Not). So only if the spec doesn't have the tag don'tRemoveGarbage will it run.

**Comment by mahendrakariya** [comment]
Gauge already has this feature! You can refer the [documentation](http://getgauge.io/documentation/user/current/advanced_readings/execution_hooks/filtering.html) for code examples.

Since this feature is already present, I am closing this issue. Feel free to reopen this issue or get in touch with us via [gitter](https://gitter.im/getgauge/chat) or [Google groups](https://groups.google.com/forum/#!forum/getgauge) if case of any questions.

**Comment by unibeck** [comment]
There isn't any "Operator.Not" documentation. Also, your Operator class doesn't implement it.

**Comment by mahendrakariya** [comment]
Sorry. My bad. I misunderstood the original description. This should be an enhancement.

**Comment by apoorvam** [comment]
We also have a request to support Tag expression while using hooks #202, which will be more flexible. But adding NOT TagAggregator should be simple.

**Comment by unibeck** [comment]
Any update on this?

**Comment by ajoecker** [comment]
it seems that this is obsolete, as https://docs.gauge.org/using.html#tagged-execution describes the NOT `!` operator

**Comment by sriv** [comment]
@unibeck not really. What @unibeck proposed was the use of tag `NOT` operator in the execution hooks. The `not` support has been supported in tag expressions so something like this should work:
```
gauge run --tags=!foo specs
```

However there is no way to tell a hook (say `BeforeSpec`) to run for all Specs, except those tagged with `foo`.

**Comment by ajoecker** [comment]
oh yeah - read it wrong....

**Comment by zabil** [comment]
Closing this as an old issue. However, any PR's to fix this will be merged.
