### ISSUE TITLE
After installing gauge 0.8.0 windows installer system PATH variable contains only C:\Program Files\Gauge\bin

### ISSUE THREAD

**Issue by 573** [getgauge/gauge#572]
... which renders system basically unusable.

**Comment by 573** [comment]
Workaround: https://answers.microsoft.com/en-us/windows/forum/all/reset-default-windows-7-ultimate-path-variables/b35ea8e9-4256-e011-8dfc-68b599b31bf5

**Comment by sriv** [comment]
Sorry to hear this - which OS flavour are you seeing this behaviour? I am on Win10 x64 and I do not see the PATH being overwritten.

**Comment by sriv** [comment]
Looks like this could be similar to #150.

Basically, this happens if the existing path length is greater than 1024 characters. Gauge uses NSIS to build the installer, and NSIS wiki recommends that we use [special builds](http://nsis.sourceforge.net/Special_Builds) of NSIS to generate the installer, to support 8192 characters.

This requires a change to the gauge windows build agents.

**Comment by 573** [comment]
I see that. It is "Version	6.1.7601 Service Pack 1 Build 7601".

**Comment by sriv** [comment]
@573 Thanks for the info. I have updated our build agent to use the Long String builds of NSIS, so the forthcoming installers should not have this behaviour. Will test it and report back.

If this is a blocker, I can update the installers of gauge 0.8.0 post that.

**Comment by sriv** [comment]
updated build agent to use Special Build of NSIS. Should support 8192 character strings.

**Comment by sguptatw** [comment]
Unable to test this due to #589

**Comment by sguptatw** [comment]
working with path length greater than 1024 characters
