### ISSUE TITLE
refactor should validate input syntax

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#63]
Do we allow dynamic parameters? If we do, then the implementation is broken. Note the output of refactor below.

```
gauge --refactor "A context step which gets executed before every scenario" "A context step which gets executed before every scenario with
<foo> and <bar>"
```

Resuts in

Spec:
```
* A context step which gets executed before every scenario with "" and ""

```

Implementation:
```
step 'A context step which gets executed before every scenario with {} and {}' do |foo, bar|
end
```

**Comment by prateekbaheti** [comment]
That is expected behaviour. If an existing dynamic parameter is reordered, then it should be reflect accordingly, but in the case that new parameters are added, they are treated as static values.

We could use the placeholder values instead of empty static args is what i think.

 * A context step which gets executed before every scenario with "foo" and "bar"

**Comment by prateekbaheti** [comment]
Refactoring does not add empty parameter values now. ```<>``` are used only as placeholders and mark positions where a parameter needs to be added or moved.

Existing dynamic/static/special parameters will be moved based on the new position of the parameter and new parameters will always be static values.
