### ISSUE TITLE
Add flag for ordering specs

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge#641]
Introduce a flag `--order` which accepts two values - sort and random.

- `--order=sort` sorts the specs alphabetically.
- `--order=random` randomises the order in which the specs are executed.
- If the flag is not specified, the order of the specs specified by the user/file system is maintained.
- The `--sort` flag will throw a deprecation warning. And will be defaulted to `--order=sort`.

**Comment by sguptatw** [comment]
consider parallel with eager for sorting

**Comment by nehashri** [comment]
Running parallel with eager strategy and using order=sort, distributes the specs equally to the number of streams given. The execution of specs within these streams is in alphabetical order.

**Comment by sguptatw** [comment]
Todo:- Test with non-English UTF-8 chars

**Comment by sguptatw** [comment]
gauge $(ls specs/*) this can also be used to pass specs in order
To check if something similar can be done in Windows.

If that is feasible, we will not need the --sort logic in Gauge

**Comment by kupna** [comment]
I think I got a problem because of this feature:

https://github.com/getgauge/gauge/issues/652

Thanks for help.

**Comment by sriv** [comment]
@kupna - this feature is yet to be released. We are contemplating removing the sorting logic in Gauge since the operating system commands do it well. 

If you think this is a bad idea, please do comment.

**Comment by navaneeth** [comment]
I think it is a bad idea because this will let people write specs which are dependent on each other. By default, Gauge should not guarantee any order of execution.

**Comment by RabihHallage** [comment]
Hello @sriv,
Please do not remove this feature, so far this feature have saved our team from wasting time on implementing any logic to sort specs.
In our case we are using gauge within our CI platform  and we don't want to include script files or additional logic outside gauge to order spec files!

**Comment by sriv** [comment]
Hello @RabihHallage , thank you for the feedback.

We have presently decided to remove the newly introduced `--order` flag since it seems to add to confusion. Gauge shall continue to have the `--sort` flag, however we recommend that it be used judiciously, and if possible be avoided. 

The use of `--sort` could be an indication that your specs/scenarios are inter-dependant, which is not recommended.

**Comment by sguptatw** [comment]
To brainstorm the expected behavior. Here is the notes from an earlier discussion.

Notes: Expected behavior
The specs will be executed in the order provided by the user.
* If the user has specified a spec multiple times, the spec will get executed multiple times in the given order.
* If sort and user input is given, then sort will take priority.
If the user chooses to use --sort the following behavior will be applied
Specs will be sorted based on depth first.
Specs will be sorted based on the file names(full path) and not the specification name.

**Comment by sguptatw** [comment]
**Expected behavior**
The specs should be sorted based on the file names based on the ascii values.

**Actual behavior**
The specs are not getting sorted.
The order of execution is
* 002 Restricted
* 003 Reserved
* 10 Blah
* 001 Example

**Steps to replicate**
[test.zip](https://github.com/getgauge/gauge/files/1054338/test.zip)
Execute from command line
```
gauge --sort specs
```

**Version**
```
Gauge version: 0.8.5.nightly-2017-06-01

Plugins
-------
html-report (4.0.0.nightly-2017-05-04)
java (0.6.3.nightly-2017-05-26)
ruby (0.4.1.nightly-2017-05-08)
xml-report (0.2.0)
```

**Comment by sguptatw** [comment]
getting an exception on executing with tags
```
gauge --tags="z|b|a" --sort specs
```
panic: <nil> not an Int

goroutine 1 [running]:
go/constant.Uint64Val(0x0, 0x0, 0x0, 0x421cb4660)
	/usr/local/Cellar/go/1.8.3/libexec/src/go/constant/value.go:420 +0x1ef
github.com/getgauge/gauge/filter.(*ScenarioFilterBasedOnTags).evaluateExp(0x421c384e0, 0x421c4e9e0, 0x14, 0x421c4e9e0, 0x14, 0x5)
	/tmp/src/github.com/getgauge/gauge/filter/specItemFilter.go:145 +0x28b
github.com/getgauge/gauge/filter.(*ScenarioFilterBasedOnTags).formatAndEvaluateExpression(0x421c384e0, 0x421c38510, 0x421b057b8, 0x421cc2808, 0x0, 0x0)
	/tmp/src/github.com/getgauge/gauge/filter/specItemFilter.go:86 +0x24c
github.com/getgauge/gauge/filter.(*ScenarioFilterBasedOnTags).filterTags(0x421c384e0, 0x421ac0f60, 0x1, 0x1, 0x28)
	/tmp/src/github.com/getgauge/gauge/filter/specItemFilter.go:71 +0x17a
github.com/getgauge/gauge/filter.(*ScenarioFilterBasedOnTags).Filter(0x421c384e0, 0x18884a0, 0x421c40000, 0x0)
	/tmp/src/github.com/getgauge/gauge/filter/specItemFilter.go:58 +0x1f5
github.com/getgauge/gauge/gauge.(*Specification).Filter(0x421ae2600, 0x1888320, 0x421c384e0)
	/tmp/src/github.com/getgauge/gauge/gauge/specification.go:261 +0x6d
github.com/getgauge/gauge/filter.filterSpecsByTags(0x421c4e800, 0x4, 0x4, 0x7fff5fbff8bd, 0x5, 0x421cf4000, 0x421bbc000, 0x84219b82c0)
	/tmp/src/github.com/getgauge/gauge/filter/specItemFilter.go:194 +0x18f
github.com/getgauge/gauge/filter.(*tagsFilter).filter(0x421cb4290, 0x421c4e800, 0x4, 0x4, 0x100f348, 0x10, 0x15819c0)
	/tmp/src/github.com/getgauge/gauge/filter/specsFilter.go:41 +0xa3
github.com/getgauge/gauge/filter.applyFilters(0x421c4e800, 0x4, 0x4, 0x421b05a88, 0x2, 0x2, 0x0, 0x0, 0x0)
	/tmp/src/github.com/getgauge/gauge/filter/filter.go:30 +0x6c
github.com/getgauge/gauge/filter.FilterSpecs(0x421c4e800, 0x4, 0x4, 0x1, 0x421b2d920, 0x421c4e800)
	/tmp/src/github.com/getgauge/gauge/filter/filter.go:14 +0x149
github.com/getgauge/gauge/parser.ParseSpecs(0x4219c42b0, 0x1, 0x1, 0x421acf690, 0x421b2d920, 0x421b05b88, 0x0, 0x0, 0x0)
	/tmp/src/github.com/getgauge/gauge/parser/parse.go:67 +0x85
github.com/getgauge/gauge/validation.ValidateSpecs(0x4219c42b0, 0x1, 0x1, 0x421b05d00, 0x421ae5f68)
	/tmp/src/github.com/getgauge/gauge/validation/validate.go:146 +0x446
github.com/getgauge/gauge/execution.ExecuteSpecs(0x4219c42b0, 0x1, 0x1, 0x0)
	/tmp/src/github.com/getgauge/gauge/execution/execute.go:98 +0xa1
main.main()
	/Users/vagrant/go-agent-17.4.0/pipelines/Gauge-Nightly/gauge.go:154 +0x487

**Comment by sriv** [comment]
@sguptatw - in your example the `001 Example` spec has a special character in its name. Please check and see if that is intentional.
