### ISSUE TITLE
Ability to protect password in specs

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#643]
**Expected behavior**
Though the data used in tests are dummy. Consider an option to protect the passwords from being reflected in the specifications.

**Actual behavior**
The password is visible in the specifications. Even if a file input is used, the password has to be checked in.

**Feature request**
Option to protect password.

**Comment by sriv** [comment]
The best way to protect a secret is to not have it in the spec or in the project. If it has to be version controlled, it should be encrypted with sufficient protection.

Rather than having Gauge own up securing secrets, I propose the use of environment variables to pass secrets.

Thus, with current release (0.8.3) the step could look like:

```
* Login as "admin" with password from "APP_ADMIN_PASSWORD"
```

And the implementation would read the environment var `APP_ADMIN_PASSWORD` and use it to login.

This can be made less cumbersome by introducing a new special parameter of type `env`, that would make the above step look like:

```
* Login as "admin" with password <env:APP_ADMIN_PASSWORD>
```
Gauge will then pass the password to the implementation after reading `ENV[APP_ADMIN_PASSWORD]`.

**Comment by zabil** [comment]
> * Login as "admin" with password from "APP_ADMIN_PASSWORD"

Is good enough, introducing special tokens reduces the readability of the specs and ties the spec to the environment variable usage when the implementation must decide that instead.
