### ISSUE TITLE
Add an option to --dry-run gauge specs

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge#655]
Let the tester do a `--dry-run` to see specification execution order.

```
$ gauge --init java
$ gauge specs --dry-run 
# Specification Heading
  ## Vowel counts in single word	 
  ## Vowel counts in multiple word	 
```

As the name suggests, Gauge must not execute the specifications.

**Comment by jackperalta** [comment]
What shall happen with hooks and or reports ? shall they be triggered and/or created ? Or nothing at all ? Or some of the hooks e.g. ?

**Comment by nehashri** [comment]
Nothing will be triggered. It is a read only operation that tells which specs/scenarios will be executed.

**Comment by nehashri** [comment]
**Question**
- what should be the output if parallel flag is given?
Should the console list all specifications/scenarios per runner, similar to the execution stage?
- Should the dry run flag try and validate all specifications too? (This would mean compiling and bringing up the runner to validate all steps)

**Comment by sriv** [comment]
> what should be the output if parallel flag is given?

Gauge's output (html-report etc) do not differ if it were run in parallel/serial. Going by that fact, I'd say dry run need not change too. 

> Should the dry run flag try and validate all specifications too? (This would mean compiling and bringing up the runner to validate all steps)

This is something we should seek inputs from the community on. Without validation, dry run would be faster, but potentially inaccurate. If the primary usage of dry run is to figure out the applicable specs/scenarios given a filter criteria then I guess gauge need not validate specs. But I feel it would be good to validate, since dry run would then accurately list the scenarios that would get listed.

Side note, if dry run ends up validating, `--validate` becomes redundant.

**Comment by ajoecker** [comment]
Personally I would vote for validating when doing the dry run. I see the dry run as a "what if" situation. What if I really start that.... I would be confused if dry run runs through and then I start and this fails due to validation. I would expect a dry run shows me what would happen if i press the big red button.

**Comment by MolineroUA** [comment]
Hi! I agree with @ajoecker that validation would be a great addition for dry run. Or, as variant, to add possibility to activate the validation from a command
> gauge specs --dry-run 
> gauge specs --dry-run  validate

**Comment by Thunderforge** [comment]
What are the expected durations for the validation portion and the other dry run operations? Are we expecting these to be a matter of seconds?

If both of them are relatively fast, even on large projects, I don't see the downside of pairing them together as part of `--dry-run`. If one or the other is going to take something on the scale of minutes or more, then I could potentially see them being separated.

That said, I would be in favor of `--dry-run` having validation on by default in order to reduce the amount of surprise. If one of the operations takes a long time, I would be in favor of a `--no-validate` option or keeping the `validate` command, whichever makes more sense.

**Comment by ajoecker** [comment]
that sounds like a good point @Thunderforge . A dry run should not take so long as the actual execution, so there should be the possibility to switch of validation (in case validation becomes turned on per default).

Regarding parallel running. I have not enough experience with this option. From my naive point of view - this does not matter for me. How this is then from which runner executed is for me irrelevant. I want to see, that a) I can execute my specs (validation) and which specs are going to be executed

**Comment by nehashri** [comment]
> What are the expected durations for the validation portion and the other dry run operations? Are we expecting these to be a matter of seconds?

Validation duration should be quite small in some languages. It requires the runner to be started, so in case of languages like Java, C# it requires the project code to be built first. Also, Validation time increases with a huge test suite, though I feel that this time will be quite small. So all in all, you can say that the duration for validation phase will be mostly dependent on the time it takes to start the runner (compile, build, any other task to bring the runner up).

Another Question that needs some clarification is 
> What should be the output if parallel flag is given?

When running with dry-run, it is not possible to determine which specification is executed in a given parallel stream. I would like to know if this is really useful information.

**Comment by Thunderforge** [comment]
@zabil Is this being closed because it’s been implemented?

**Comment by zabil** [comment]
@Thunderforge this feature won't be implemented as it's difficult to define what's a part of the dry run as well as implement.
