### ISSUE TITLE
Getting warnings for old usages while gauge init ruby

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#692]
Expected behavior
We should not get old usage warnings when executing it as a part of other commands. The old usages in other commands should be replaced with new usages.

Actual behavior
We are getting warning while gauge init ruby
Warning: '-v' is deprecated, it will be removed soon. See usage.
Warning: '--machine-readable' is deprecated, it will be removed soon. See usage.

**Version**
```
Gauge version: 0.9.0.nightly-2017-06-28

Plugins
-------
csharp (0.10.1)
html-report (4.0.1.nightly-2017-06-27)
java (0.6.5.nightly-2017-06-28)
ruby (0.4.1)
spectacle (0.1.2)
xml-report (0.2.0)
```

**Comment by sriv** [comment]
this is because the ruby template [looks at](https://github.com/getgauge/gauge-repository/blob/master/templates/ruby/create_gemfile.rb#L4) `gauge -v` to determine the version it should add to gemfile.

We cannot change this, since the live version of gauge uses this. 

Sidenote: we should no print `warning` when doing `machine-readable`. The output is not valid jsob.

**Comment by sriv** [comment]
@sguptatw  - still relevant?
