### ISSUE TITLE
Usage of --failed flag in jenkins And Eclipse

### ISSUE THREAD

**Issue by RafeesRahim** [getgauge/gauge#703]
Hi ,
Anyone please help how we can run the failed cases in jenkins and eclipse.

### Expected behavior
Should run failed cases

### Actual behavior
Not running the failed cases

### Gauge version
Plugins
-------
go (0.1.1)
html-report (3.1.0)
java (0.6.3)
xml-report (0.2.0)

**Comment by sriv** [comment]
Query raised and answered in forum: https://groups.google.com/d/msg/getgauge/lKeMRidPjos/AnchhvKtAAAJ

**Comment by RafeesRahim** [comment]
hi @sriv could you please help me how to use the above tag in jenkins?

**Comment by sriv** [comment]
Hi @RafeesRahim - for running the job, it is just a matter of invoking gauge with `--failed`. 

I imagine something like this:

- Create a Job to run `mvn gauge:execute`. Lets call it Job-1.
- Create another Job to run failed tests, (use this command `mvn gauge:execute -Dflags="--failed"`). Lets call it Job-2.
- Model it such that Job-2 triggers as a Post Build Event on Job-1. Note that Job-1 will fail, so you cannot use the "success" trigger.
- At the end, you will see Job-1 running and triggering Job-2.

This will ensure that failures of Job-1 will get executed again in Job-2.

Again, I am not sure what is your use case, but something like the above is definitely not recommended, since it indicates that the tests are flaky and you will end up masking the underlying issues.

Hope this helps.
