### ISSUE TITLE
Allow substitution of Env properties

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge#866]
### Expected behavior
When an env variable set in shell is substituted in the env.properties then the value of the env var is set as part fo the property. 

### Steps to reproduce
1. `export test=value` in shell
2. Add a property in `default.properties` that substitutes `test` E.g. `my_env = ${test}`
3. Now try to use `my_env` variable in the tests
4. The output of `my_env` should be `value`.

You should also be able to substitute a variable from the properites file.

**Comment by kashishm** [comment]
This will be available in nightly >= 21/11/2017

**Comment by kashishm** [comment]
@haroon-sheikh Following are some issues with the current implementation.
* The current implementation is dependent on the iteration order of the map [`envVars`](https://github.com/getgauge/gauge/blob/master/env/env.go#L133) map and doesn't resolve nested properties.
```
p1 = value1
p2 = ${p1}/value2
p3 = {p2}/value3
```
**Iteration order**
`p1` -> `p2` -> `p3` works for this scenario

`p1` -> `p3` -> `p2` and `p3` -> `p2` -> `p1` doesn't works for these scenarios

**output for cases where it doesn't work**
```
p1 = value1
p3 = ${p1}/value2/value3
p2 = value1/value2
```
**Expected output**
```
p1 = value1
p3 = value1/value2/value3
p2 = value1/value2
```
One of the unit test `TestLoadDefaultEnvWithSubstitutedVariables` is also flaky because of this reason.

* Handle cyclic resolve issue
```
p1 = ${p2}
p2 = ${p1}
```

I have disabled this feature for now as we are close to a release.

**Comment by haroon-sheikh** [comment]
I'm looking at these issues now.

**Comment by haroon-sheikh** [comment]
@kashishm I've limited the feature so that it only allows externally set vars to be substituted.

There isn't an easy way to fix the substitution of properties vars as it'll require N times of iterations and order of maps isn't guaranteed.

**Comment by nehashri** [comment]
### Updated behaviour
When an env variable set in shell is substituted in the env.properties then the value of the env var is set as part fo the property.

#### Steps to reproduce
- export test=value in shell
- Add a property in default.properties that substitutes test E.g. my_env = ${test}
- Now try to use my_env variable in the tests
- The output of my_env should be value.

Properties defined in the properties file will **not** be substituted.

**Comment by nehashri** [comment]
The fix should be available in nightly >= 27-11-2017
