### ISSUE TITLE
diagnostics should get updated after a concept is implemented

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#977]
**Expected behavior**
The specification should not show the newly created concept as unimplemented.
The diagnostics of the concept file where the new concept is created should work seamlessly.

**Actual behavior**
- The step is still marked as unimplemented. However navigation to the newly created concept is working as expected.
- Adding a concept to an existing/new file does not highlight unimplemented steps.

**Version**
```
Gauge version: 0.9.8.nightly-2018-03-14
Commit Hash: b285ea3

Plugins
-------
csharp (0.10.2.nightly-2018-03-12)
html-report (4.0.4.nightly-2018-02-23)
java (0.6.7.nightly-2018-03-12)
js (2.2.0.nightly-2018-03-14)
python (0.2.4.nightly-2018-03-12)
ruby (0.4.3.nightly-2018-03-12)
```
Bug on story - https://github.com/getgauge/gauge-vscode/issues/192

**Comment by sguptatw** [comment]
Since the diagnostics of unimplemented step is displayed, the  user is able implement the same step text multiple times.

**Comment by Apoorva-GA** [comment]
Steps I fallowed to replicate: 

* add a new step `* abc ` in spec file(`* abc` marked as undefined)
* implement the `* abc`  as concept in a new concept file (`* abc` not marked as undefined)
* add a new step to concept file and the newly added step is marked as undefined, which implies  concept file's diagnostics are working.

Isn't this the expected behaviour?

if not can you please give some steps to replicate.

**Comment by sguptatw** [comment]
This happens on OS `Windows`.
**Observation**
This happens when I open the spec file in Windows  with a double click.
(With a single click, when you navigate between spec/cpt/impl files the original file is closed. However with a double click, the original file is open)

**Comment by sguptatw** [comment]
This happens on OS `Windows`.

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge nightly >= 06/04/18
