### ISSUE TITLE
Remove telemetry before 1.0

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#981]
_From @sguptatw on March 20, 2018 5:6_

[Telemetry data](https://blog.getgauge.io/why-we-collect-data-b19df366b677) was collected for Gauge.

Now that we have gathered the information we seeked, we want to remove the data collection before Gauge 1.0 Release

_Copied from original issue: getgauge/gauge-vscode#206_

**Comment by nehashri** [comment]
We would like to have the data, and since we don't capture any personally identifiable data it should be fine

**Comment by bodiam** [comment]
I'm surprised that you can say such a thing. It's not your data you're capturing. I almost started promoting Gauge in my office, but this turns Gauge into a piece of spyware, and I'm not a big fan of promoting spyware. This would be a blocker for me and for the company I work for, and I'd request to remove this feature from Gauge.

**Comment by zabil** [comment]
Hi @bodiam,

Thanks for trying out Gauge and promoting it. 

Here is an easy (IMO) way to turn of telemetry in gauge, if you prefer - https://manpage.gauge.org/gauge_telemetry.html

You may also set `GAUGE_TELEMETRY_ENABLED`  environment variable to be `false`. This may be of use in your CI/CD infrastructure.

I'd like to go into some detail regarding the data collected, since you classified Gauge as a spyware.

- Gauge does not collect any personal information. It even [anonymizes your IP](https://github.com/getgauge/gauge/blob/master/track/track.go#L70) when sending events to Google Analytics.
- You can see the insights Gauge gathers [here](https://insights.gauge.org/)
- If you wish to see every request that is sent, you can [turn on logging for telemetry](https://manpage.gauge.org/gauge_telemetry_log.html). This will dump the raw http request on your console.
- Gauge is 100% open source (yes, even our website code is on github). This is relevant for two reasons:
 - You are welcome to audit the code to see what exactly is happening. The tracking logic resides [here](https://github.com/getgauge/gauge/tree/master/track)
 - You can build gauge for yourself and be reassured that there is no build time magic happening to inject any tracking. In fact, gauge supports a build using `go get`, which always builds from source.

This [blog post](https://gauge.org/2017/07/20/why-we-collect-data/) is an attempt to explain why Gauge has this feature, and how it helps the maintainers.

We understand if this is a blocker for you for adopting Gauge. However we need this to make Gauge a better product and we've made it very easy to turn it off.

You are welcome to see the [original issue](https://github.com/getgauge/gauge/issues/658) for this feature, if you wish to.

**Comment by bodiam** [comment]
Hi @zabil ,

I appreciate the time you took for this writeup, and thanks for getting back to me. I don't applaud the data collection part, but I even more object to the way you do it. I find it questionable that this happens out of the box, that the command line client doesn't mention it all, that it's not transparent or even mentioned in the documentation page that, or what, it's collecting, and that on the getting started page it's literally the smallest text on the page.

All of these things combined give me the impression that you're trying to hide the fact that's you're collecting data (yes, it's listed, somewhere, in a github issue somewhere), but by default, for every user this data collection is turned on without making them aware of this. 

Making it a better product can be done by properly informing the users of your product. However, for now, Gauge (even though it seems a really nice project, and solves a few issues we're having with Cucumber), will be a product we won't adopt, but we might copy some ideas in to our Cucumber suite for this.

Thanks again for your work on this product!

**Comment by zabil** [comment]
> However, for now, Gauge (even though it seems a really nice project, and solves a few issues we're having with Cucumber), will be a product we won't adopt, but we might copy some ideas in to our Cucumber suite for this.

:+1:

**Comment by zabil** [comment]
Refer https://github.com/getgauge/gauge.org/issues/100 for changes to telemetry messaging on website.
