### ISSUE TITLE
Step generation should not consider parameter values to generate placeholder names

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#992]
**Expected behavior**
The step annotation text should have parameter placeholder names independent of parameter values

**Actual behavior**
The names generated for the annotation is based on the parameter value

**Steps to replicate**
* Create a `gauge-java` project
* Create a step `Upload file <file:specs/something.txt>`
* Generate the implementation
> The implementation has the file path mentioned in the annotation text
    @Step("Upload file <file:specs/something.txt>")
    public void implementation1(Object arg0) {
    }

**Version**
```
Gauge version: 0.9.8.nightly-2018-03-29
Commit Hash: b79de74

Plugins
-------
html-report (4.0.4.nightly-2018-03-28)
java (0.6.7.nightly-2018-03-16)
screenshot (0.0.1)
```

**Comment by jackperalta** [comment]
is this gauge core doing that ? I assumed it would be the IDE plugin ?

**Comment by sguptatw** [comment]
@jackperalta The gauge core does it for the annotation text of the step. The implementation signature is taken care of by the language runner. The IDE only reflects the changes made.

**Comment by jackperalta** [comment]
is there any wanted placeholder that should be used instead ? I simply have `parameter` now in place

**Comment by nehashri** [comment]
This issues needs to be fixed in the respective runners. It does not need a change in Gauge core itself. The annotation text generated by Gauge seems to be fine.

**Comment by jackperalta** [comment]
are you sure @nehashri ? 

In `stepParser.go` in 121, the `argText` is used, which seems to become `<file:specs/something.txt>` e.g.

And if I change only this line and not the runner, I do get the change in a newly created method

**Comment by nehashri** [comment]
@jackperalta There may be a way to fix this in gauge too. The file `stepParser.go` is used to parse the file. At this stage it is useful to retain the actual step value with the special param values as it has implications downstream. In this stage, only the partial tokens of a spec file is generated. The actual `Step` object is created later on. The `Step` is then converted to a `StepValue` object and then to a `ProtoStepValue` object which is passed on to the runner.
The `Step` object is used in many places and changing the `Step` object can create unexpected results and may not generate the correct `StepValue` in some cases.
So, I advice you not to change the behaviour before `StepValue` object is created. 

Gauge cannot determine the correct annotation text or parameter names. The runner will have to do some kind of processing so that language specific keywords (and other characters) are removed. 
The java runner (or some other runners) don't seem to be doing this kind of processing when a step implementation suggestion is generated. 
Gauge can only help in someway by passing a little better annotation text to the runners. The runners still need to sanitize the text.
So, looking at the issue, there needs to be a fix on the runners too.

**Comment by jackperalta** [comment]
I have to admit I could not find a location in the java runner, where this should happen. Also from my understanding this seems more a gauge-core <-> IDE plugin issue and not a runner thingy.

**Comment by nehashri** [comment]
@jackperalta In runner, the parameter names and others should be sanitized. The runner is responsible for giving the suggestion(step generation). However in Intellij, it the way a step is handled is quite different.

**Comment by zabil** [comment]
Closing this as Gauge will not be implementing this feature.
